# Does Air Quality affect COVID-19 Mortality?

## Problem
*As of January 10th, 2021*

![covid_header](./img/covid.jpg)
*Source: https://www.health.pa.gov/topics/disease/coronavirus/PublishingImages/COVID-19%20Header.jpg*

**What is COVID-19? How does it spread?**

Coronavirus Disease 19 ("COVID-19") is a contagious disease first discovered in Wuhan, China on December 2019. Within a month, the first case outside the country was discovered in Thailand and later the United States (January 21). Rapid spread including significant increases in disease-related hospitalizations and deaths continued while the public, government, and the health care communities scrambed to respond to what was then (and still is) an unknown disease. On March 10th 2020, the World Health Organization (WHO) declared COVID-19 **a global pandemic** ([Source](https://www.who.int/news/item/27-04-2020-who-timeline---covid-19)). 

Unlike other known [coronaviruses](https://www.cdc.gov/coronavirus/types.html) which typically cause mild to moderate upper-respiratory tract illness, COVID-19 can cause severe illness and even death ([Source](https://www.nih.gov/news-events/nih-research-matters/immune-cells-common-cold-may-recognize-sars-cov-2#:~:text=Coronaviruses%20usually%20cause%20mild%20to,illness%20and%20even%20death.)). As per The Centers for Disease Control and Prevention (CDC), COVID-19 ["spreads through **respiratory droplets or small particles**, such as those in aerosols, produced when an infected person coughs, sneezes, sings, talks, or breathes. These particles can be **inhaled into the nose, mouth, airways, and lungs and cause infection**."](https://www.cdc.gov/coronavirus/2019-ncov/faq.html#Basics). Treatment against the disease is still in development with many theories including herd immunity considered and later disproven along the way. The U.S. Food and Drug Administration (FDA) has approved one experimental drug (Remdesevir) to treat  existing patients and taken the extreme measure of allowing healthcare providers (under certain conditions) to use products not yet approved ([Source](https://www.cdc.gov/coronavirus/2019-ncov/your-health/treatments-for-severe-illness.html)). On the preventative side, government has implemented public measures to decrease **community spread** including lockdowns and mask mandates. Meanwhile, vaccine efforts were accelerated due to government action across the world including the U.S. [Operation Warp Speed](https://www.hhs.gov/coronavirus/explaining-operation-warp-speed/index.html). The first U.S. COVID-19 vaccine, outside clinical trials, was administered on December 2020 (only a year after the disease was first heard of) and national distribution efforts are under way.


**Who has an increased risk of developing severe illness from COVID-19 (in the United States)?**

As [per the CDC](https://www.cdc.gov/coronavirus/2019-ncov/faq.html#Basics), the following people have an increased risk of developing severe illness from COVID-19:
* Older adults
* People of all ages with certain underlying medical conditions
* Pregnant people are also at increased risk for severe illness from COVID-19.

The CDC also [states](https://www.cdc.gov/coronavirus/2019-ncov/faq.html#Basics): **"Long-standing systemic health and social inequities have put many people from racial and ethnic minority groups at increased risk of getting sick and dying from COVID-19."** This inequality is most evident in the rate of deaths. A black (or African American) and Hispanic (or Latino) person is 2.8X more likely to die from COVID-19 than a White (Non-Hispanic) person. An American Indian (or Alaska Native) is 2.6X more likely ([Source](https://www.cdc.gov/coronavirus/2019-ncov/covid-data/investigations-discovery/hospitalization-death-by-race-ethnicity.html)).


**PROBLEM: Given that COVID-19 is transmmitted via respiratory particles and the unfair inqequalities in its mortality rate, can something be done to prevent or decrease its effects?**


## Project Scope

Since before COVID-19's discovery, there has been public debate related to the existence and actions to take against climate change (particularly air pollution). Air pollution was heavily politized through the 2015 passage (and 2017 repeal) of the [Clean Power Plan](https://archive.epa.gov/epa/cleanpowerplan/fact-sheet-overview-clean-power-plan.html) aimed at reducing carbon pollution from power plants and the 2019 introduction of the [Green New Deal](https://www.congress.gov/116/bills/hres109/BILLS-116hres109ih.pdf) package.

As the country faces a devastating disease which spreads through air particles and the government considers climate change legislation, it is crucial to consider: **Does air quality affect Covid-19 mortality?**

As the timeline and implementation of disease mitigation efforts differs widely between states, a look at one state where all counties have the same legislation (for the most part) is more meaningful. This project will look at **New York State** whose regions display a wide range of conditions that may affect air quality such as population density, racial makeup, income level, etc.

## Objective: 

Answer: **Does air quality affect COVID-19 mortality in New York State?**

To answer this question, this project will compare the following data per county:
* COVID-19 Deaths
* Air Quality
* Demographics


## Data Sources

**COVID-19 Deaths**

Total
* Source: The U.S. Centers for Disease Control and Prevention (CDC)
* Link: [Coronavirus Cases & Deaths](https://data.cdc.gov/NCHS/Provisional-COVID-19-Death-Counts-in-the-United-St/kn79-hsxy)

Daily Count
* Source: USAFacts.org
* Link: [New York Coronavirus Cases & Deaths](https://usafacts.org/visualizations/coronavirus-covid-19-spread-map/state/new-york)

**Air Quality**
* Source: U.S. Environmental Protection Agency (EPA)
* Links: 
    * [Outdoor Air Quality Data](https://www.epa.gov/outdoor-air-quality-data/download-daily-data) 
        * *Data Dictionary [here](https://www.epa.gov/outdoor-air-quality-data/about-air-data-reports)*
    * [Air Quality Index Breakpoints](https://aqs.epa.gov/aqsweb/documents/codetables/aqi_breakpoints.html) (as of January 11, 2021)

**Demographics**
* Source: U.S. Census Bureau
* Links
    * [County Population by Characteristics: 2010-2019](https://www.census.gov/data/tables/time-series/demo/popest/2010s-counties-detail.html) 
        1) Age Group and Sex 
        2) Age, Sex, Race, Hispanic Origin


* Source: U.S. Department of Agriculture (USDA)
* Links:
    * [County-Level Data: Poverty](https://www.ers.usda.gov/data-products/county-level-data-sets/)
    * [County-Level Data: Unemployment and Household Income](https://www.ers.usda.gov/data-products/county-level-data-sets/)
    * [Hospitals](https://hifld-geoplatform.opendata.arcgis.com/datasets/hospitals/data)
    
* Source: New York State Department of Health
    * Link: [Population, Land Area, and Population Density by County, New York State - 2006](https://www.health.ny.gov/statistics/vital_statistics/2006/table02.htm) (Manually extracted square miles data)
    
**Covid Deaths Demographics**

* Source: The U.S. Centers for Disease Control and Prevention (CDC)
    * Link: [Provisional COVID-19 Death Counts by County and Race](https://data.cdc.gov/NCHS/Provisional-COVID-19-Death-Counts-by-County-and-Ra/k8wy-p9cg)


## Agenda  <a class="anchor" id="agenda"></a>

1. [Additional Research](#research): FIPS & AIr Quality
2. [Data Upload & Preview](#data)
3. [Data PreProcessing](#datacleaning)
4. [Exploratory Data Analysis](#eda)
5. [Hypothesis Test](#htest): "Covid-19 mortality rate is different between counties improving their air quality and counties were air quality is deteriorating."
6. [Regression Analysis](#regression)
7. [Conclusion(s)](#conclusion)
    * Findings
    * Recommendations
8. [Poject Next Step](#next)


## 1) Additional Research <a class="anchor" id="research"></a>

## How to uniquely identify regions?

All data and observations will be made at the county level. Counties (and states) are identified by a **FIPS (U.S. Federal Information Processing Standards)**. FIPS codes originate from the National Institute of Standards and Technology (NIST), a U.S. Department of Commerce agency, to [uniquely identify a geographic area](https://transition.fcc.gov/oet/info/maps/census/fips/fips.txt#:~:text=FIPS%20codes%20are%20numbers%20which,to%20which%20the%20county%20belongs.). County FIPS Codes will be used throughtout this poject to connect multiple data sources.

## How to report on air quality?

Air Quality can be framed based on levels of different pollutants. 

The United Stated Environment Protection Agency (EPA) publishes [outdoor air quality data daily](https://www.epa.gov/outdoor-air-quality-data/download-daily-data) on the following pollutants:
* Carbon Monoxide (CO)
* NO2 (Nitrogen Dioxide)
* Ozone
* Particulate Matter 10, also known PM 10
* Particulate Matter 2.5, also known PM 2.5 (Fine Particles)
* SO2 (Sulfir Dioxide)

The scope of our project will focus on a particular region. Assuming we go with New York State, we should base our metric of air quality on what that state does. The New York State Department of Environmental Conservation (DEC) publishes air quality data on its [website](https://www.dec.ny.gov/cfmx/extapps/aqi/aqi_forecast.cfm) based on "Fine Particles", **Particulate Matter 2.5 (PM 2.5)**.


## Terms

**What is Particulate Matter?** According to the [EPA](https://www.epa.gov/pm-pollution/particulate-matter-pm-basics), particulate matter (PM) refers to "a mixture of solid particles and liquid droplets found in the air" and hence inhalable. PM10 are generally 10 micrometers (and smaller) and PM 2.5 referred to as "fine particles" are generally around 2.5 micrometers. To put into perspective, the average human hair is 70 micrometers in diameter (30 times larger than PM 2.5). These particles can be made up of hundreds of different chemicals but the most worrisome part is that they are inhaled and can cause serious health problems. "Some particles less than 10 micrometers in diameter can get deep into your lungs and some may even get into your bloodstream." A summary of health and environmental effects of particular matter can he found [HERE](https://www.epa.gov/pm-pollution/health-and-environmental-effects-particulate-matter-pm).

PM 2.5 is measured in micrograms per cubic meter (ug/m3). The EPA has set the annual PM 2.5 standard to 12 ug/m3 [Source](https://www3.epa.gov/region1/airquality/pm-aq-standards.html). NY DEC (and the EPA) usually reports an **Air Quality Index (AQI)** instead of the individual units.  

**What is AQI?** The Air Quality Index (AQI) is a scale from 0 to 500 that provides an indicator of the quality of air and its health effects. 101 typically corresponds to the level that starts being "unhealthy for sensitive groups". It can be based on the amount of PM2.5 found in the air. 

Below is a picture of the current scale posted by NY DEC [here](https://www.dec.ny.gov/cfmx/extapps/aqi/aqi_info.cfm#AQI).

![NY DEC AQI Scale](./img/ny_aqi.jpg)


## 2) Data Upload & Preview <a class="anchor" id="data"></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

**COVID-19 Deaths**

In [2]:
covid = pd.read_csv('./data/us_covid_deaths_by_county_010621.csv')

In [3]:
covid.head(2)

Date as of  First week   Last week State                   County name  \
0  01/06/2021  01/04/2020  01/02/2021    AK             Anchorage Borough   
1  01/06/2021  01/04/2020  01/02/2021    AK  Fairbanks North Star Borough   

   FIPS County Code Urban Rural Code  Deaths involving COVID-19  \
0              2020     Medium metro                        112   
1              2090      Small metro                         22   

   Deaths from All Causes  
0                    2143  
1                     509

In [4]:
covid.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1817 entries, 0 to 1816
Data columns (total 9 columns):
Date as of                   1817 non-null object
First week                   1817 non-null object
Last week                    1817 non-null object
State                        1817 non-null object
County name                  1817 non-null object
FIPS County Code             1817 non-null int64
Urban Rural Code             1817 non-null object
Deaths involving COVID-19    1817 non-null int64
Deaths from All Causes       1817 non-null int64
dtypes: int64(3), object(6)
memory usage: 127.9+ KB


In [5]:
covid.loc[covid['State']=='NY'].head()

Date as of  First week   Last week State         County name  \
1145  01/06/2021  01/04/2020  01/02/2021    NY       Albany County   
1146  01/06/2021  01/04/2020  01/02/2021    NY     Allegany County   
1147  01/06/2021  01/04/2020  01/02/2021    NY        Bronx County   
1148  01/06/2021  01/04/2020  01/02/2021    NY       Broome County   
1149  01/06/2021  01/04/2020  01/02/2021    NY  Cattaraugus County   

      FIPS County Code     Urban Rural Code  Deaths involving COVID-19  \
1145             36001         Medium metro                        310   
1146             36003              Noncore                         56   
1147             36005  Large central metro                       4454   
1148             36007          Small metro                        227   
1149             36009         Micropolitan                         29   

      Deaths from All Causes  
1145                    4121  
1146                     438  
1147                   16596  
1148                    2568  
1149                     764

In [6]:
# Is there one line per county?
covid.loc[covid['State']=='NY']['County name'].nunique() == len(covid.loc[covid['State']=='NY'])

True

This data represents the total count as of 1/6/21 which might be helpful to keep.

In [7]:
covid_total = covid.copy()
del covid

In [8]:
covid_daily = pd.read_csv('./data/ny_daily_covid_deaths_by_county_010621.csv')

In [9]:
covid_daily.columns

Index(['countyFIPS', 'County Name', 'State', 'stateFIPS', '1/22/20', '1/23/20',
       '1/24/20', '1/25/20', '1/26/20', '1/27/20',
       ...
       '12/30/20', '12/31/20', '1/1/21', '1/2/21', '1/3/21', '1/4/21',
       '1/5/21', '1/6/21', '1/7/21', '1/8/21'],
      dtype='object', length=357)

This dataset is poorly structured for analysis with each county with a row and each new date with a column. We need to restructure quickly for usage. Once restructured, we will most likely need to change the data type for dates and values.

**Air Quality**

In [10]:
aqi_breakpoints = pd.read_csv('./data/aqi_breakpoints.csv')

In [11]:
aqi_breakpoints.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87 entries, 0 to 86
Data columns (total 9 columns):
Parameter               87 non-null object
Parameter Code          87 non-null int64
Duration Code           87 non-null object
Duration Description    87 non-null object
AQI Category            87 non-null object
Low AQI                 87 non-null int64
High AQI                87 non-null int64
Low Breakpoint          87 non-null float64
High Breakpoint         87 non-null float64
dtypes: float64(2), int64(3), object(4)
memory usage: 6.2+ KB


In [12]:
aqi_breakpoints['Parameter'].unique()

array(['Acceptable PM2.5 AQI & Speciation Mass', 'Carbon monoxide',
       'Nitrogen dioxide (NO2)', 'Ozone', 'PM10 Total 0-10um STP',
       'PM2.5 - Local Conditions', 'Sulfur dioxide'], dtype=object)

Pending - preprocessing. Choose what parameters to base analysis on.

This dataset includes air quality measures for NY state based on year and pollutant - PM 2.5

In [13]:
#2020 year
air_2020 = pd.read_csv('./data/ny_air_quality_data_2020_pm2.5.csv')
air_2020['year'] = 2020

In [14]:
air_2020.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9743 entries, 0 to 9742
Data columns (total 21 columns):
Date                              9743 non-null object
Source                            9743 non-null object
Site ID                           9743 non-null int64
POC                               9743 non-null int64
Daily Mean PM2.5 Concentration    9743 non-null float64
UNITS                             9743 non-null object
DAILY_AQI_VALUE                   9743 non-null int64
Site Name                         9743 non-null object
DAILY_OBS_COUNT                   9743 non-null int64
PERCENT_COMPLETE                  9743 non-null float64
AQS_PARAMETER_CODE                9743 non-null int64
AQS_PARAMETER_DESC                9743 non-null object
CBSA_CODE                         9337 non-null float64
CBSA_NAME                         9337 non-null object
STATE_CODE                        9743 non-null int64
STATE                             9743 non-null object
COUNTY_CODE     

Multiple reports describe mobility in 2020 related to quarantine and proliferation of Work From Home policies including [this one](https://www.bloomberg.com/news/features/2020-12-17/work-from-home-tech-companies-cut-pay-of-workers-moving-out-of-big-cities). Assumingly, population has an effect on AQI and it would be better to look at AQI across many years rather than just 2020.

In [15]:
air_2019 = pd.read_csv('./data/ny_air_quality_data_2019_pm2.5.csv')
air_2019['year'] = 2019
air_2018 = pd.read_csv('./data/ny_air_quality_data_2018_pm2.5.csv')
air_2018['year'] = 2018
air_2017 = pd.read_csv('./data/ny_air_quality_data_2017_pm2.5.csv')
air_2017['year'] = 2017
air_2016 = pd.read_csv('./data/ny_air_quality_data_2016_pm2.5.csv')
air_2016['year'] = 2016
air_2015 = pd.read_csv('./data/ny_air_quality_data_2015_pm2.5.csv')
air_2015['year'] = 2015
air_2014 = pd.read_csv('./data/ny_air_quality_data_2014_pm2.5.csv')
air_2014['year'] = 2014
air_2013 = pd.read_csv('./data/ny_air_quality_data_2013_pm2.5.csv')
air_2013['year'] = 2013
air_2012 = pd.read_csv('./data/ny_air_quality_data_2012_pm2.5.csv')
air_2012['year'] = 2012
air_2011 = pd.read_csv('./data/ny_air_quality_data_2011_pm2.5.csv')
air_2011['year'] = 2011
air_2010 = pd.read_csv('./data/ny_air_quality_data_2010_pm2.5.csv')
air_2010['year'] = 2010

In [16]:
air_2010_2020 = pd.concat([air_2010, air_2011,air_2012,air_2013,air_2014,air_2015,air_2016,air_2017,air_2018,air_2019,air_2020], ignore_index=True)

In [17]:
air_2010_2020.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133889 entries, 0 to 133888
Data columns (total 21 columns):
Date                              133889 non-null object
Source                            133889 non-null object
Site ID                           133889 non-null int64
POC                               133889 non-null int64
Daily Mean PM2.5 Concentration    133889 non-null float64
UNITS                             133889 non-null object
DAILY_AQI_VALUE                   133889 non-null int64
Site Name                         133889 non-null object
DAILY_OBS_COUNT                   133889 non-null int64
PERCENT_COMPLETE                  133889 non-null float64
AQS_PARAMETER_CODE                133889 non-null int64
AQS_PARAMETER_DESC                133889 non-null object
CBSA_CODE                         129652 non-null float64
CBSA_NAME                         129652 non-null object
STATE_CODE                        133889 non-null int64
STATE                             133

In [18]:
#are there 11 years of data?
air_2010_2020.year.unique()

array([2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020],
      dtype=int64)

In [19]:
air_2010_2020.isna().sum()

Date                                 0
Source                               0
Site ID                              0
POC                                  0
Daily Mean PM2.5 Concentration       0
UNITS                                0
DAILY_AQI_VALUE                      0
Site Name                            0
DAILY_OBS_COUNT                      0
PERCENT_COMPLETE                     0
AQS_PARAMETER_CODE                   0
AQS_PARAMETER_DESC                   0
CBSA_CODE                         4237
CBSA_NAME                         4237
STATE_CODE                           0
STATE                                0
COUNTY_CODE                          0
COUNTY                               0
SITE_LATITUDE                        0
SITE_LONGITUDE                       0
year                                 0
dtype: int64

The only column with null are CBSA related (Core Based Statistical Areas) which will not be used

In [20]:
air_2010_2020.iloc[0]

Date                                               01/01/2010
Source                                                    AQS
Site ID                                             360010005
POC                                                         1
Daily Mean PM2.5 Concentration                           22.5
UNITS                                                ug/m3 LC
DAILY_AQI_VALUE                                            73
Site Name                           ALBANY COUNTY HEALTH DEPT
DAILY_OBS_COUNT                                             1
PERCENT_COMPLETE                                          100
AQS_PARAMETER_CODE                                      88101
AQS_PARAMETER_DESC                   PM2.5 - Local Conditions
CBSA_CODE                                               10580
CBSA_NAME                         Albany-Schenectady-Troy, NY
STATE_CODE                                                 36
STATE                                                New York
COUNTY_C

In [21]:
air_2010_2020['Source'].unique()

array(['AQS', 'AirNow'], dtype=object)

In [22]:
air_2010_2020['Source'].value_counts()

AQS       133386
AirNow       503
Name: Source, dtype: int64

2 sources of data. "**AQS** data are used for regulatory purposes, such as determining attainment of the National Ambient Air Quality Standards (NAAQS), while **AirNow** data are used only to report the AQI to the public." ([Source](https://www.airnow.gov/about-the-data/#:~:text=AQS%20data%20are%20used%20for,the%20AQI%20to%20the%20public.)). Both will be used.

In [23]:
air_2010_2020['Site Name'].nunique()

50

50 sites collecting data

In [24]:
air_2010_2020['Daily Mean PM2.5 Concentration'].describe()

count    133889.000000
mean          7.550299
std           4.748374
min          -4.500000
25%           4.200000
50%           6.600000
75%           9.800000
max          71.500000
Name: Daily Mean PM2.5 Concentration, dtype: float64

In [25]:
#is percent always 100%
air_2010_2020['PERCENT_COMPLETE'].describe()

count    133889.0
mean        100.0
std           0.0
min         100.0
25%         100.0
50%         100.0
75%         100.0
max         100.0
Name: PERCENT_COMPLETE, dtype: float64

In [26]:
air_2010_2020['AQS_PARAMETER_CODE'].unique()

array([88101, 88502], dtype=int64)

In [27]:
air_2010_2020['AQS_PARAMETER_DESC'].unique()

array(['PM2.5 - Local Conditions',
       'Acceptable PM2.5 AQI & Speciation Mass'], dtype=object)

There are two parameters being reported on PM2.5 - Local Condition and Acceptable PM2.5 AQI & Specialization Mass (Codes: 88101 and 88502). According [the EPA's website](https://www.epa.gov/outdoor-air-quality-data/air-data-frequent-questions#8), when making visualizations they measure both but when reporting data they use only 88101

In [28]:
air_2010_2020['DAILY_OBS_COUNT'].describe()

count    133889.0
mean          1.0
std           0.0
min           1.0
25%           1.0
50%           1.0
75%           1.0
max           1.0
Name: DAILY_OBS_COUNT, dtype: float64

Each site has one observation per day.

In [29]:
#Confirm only NY
air_2010_2020['STATE'].unique()

array(['New York'], dtype=object)

In [30]:
air_2010_2020.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133889 entries, 0 to 133888
Data columns (total 21 columns):
Date                              133889 non-null object
Source                            133889 non-null object
Site ID                           133889 non-null int64
POC                               133889 non-null int64
Daily Mean PM2.5 Concentration    133889 non-null float64
UNITS                             133889 non-null object
DAILY_AQI_VALUE                   133889 non-null int64
Site Name                         133889 non-null object
DAILY_OBS_COUNT                   133889 non-null int64
PERCENT_COMPLETE                  133889 non-null float64
AQS_PARAMETER_CODE                133889 non-null int64
AQS_PARAMETER_DESC                133889 non-null object
CBSA_CODE                         129652 non-null float64
CBSA_NAME                         129652 non-null object
STATE_CODE                        133889 non-null int64
STATE                             133

Data updates needed
* date to datime

**County Demographics**

In [31]:
#Age Group & Sex
county_pop_by_characteristics_age_sex = pd.read_csv('./data/county_population_by_characteristics_2010-2019_age-group_sex.csv')

In [32]:
county_pop_by_characteristics_age_sex.iloc[0]

SUMLEV                        50
STATE                         36
COUNTY                         1
STNAME                  New York
CTYNAME            Albany County
                       ...      
AGE85PLUS_MALE              2104
AGE85PLUS_FEM               4996
MEDIAN_AGE_TOT              38.5
MEDIAN_AGE_MALE             36.8
MEDIAN_AGE_FEM                40
Name: 0, Length: 96, dtype: object

In [33]:
county_pop_by_characteristics_age_sex.columns

Index(['SUMLEV', 'STATE', 'COUNTY', 'STNAME', 'CTYNAME', 'YEAR', 'POPESTIMATE',
       'POPEST_MALE', 'POPEST_FEM', 'UNDER5_TOT', 'UNDER5_MALE', 'UNDER5_FEM',
       'AGE513_TOT', 'AGE513_MALE', 'AGE513_FEM', 'AGE1417_TOT',
       'AGE1417_MALE', 'AGE1417_FEM', 'AGE1824_TOT', 'AGE1824_MALE',
       'AGE1824_FEM', 'AGE16PLUS_TOT', 'AGE16PLUS_MALE', 'AGE16PLUS_FEM',
       'AGE18PLUS_TOT', 'AGE18PLUS_MALE', 'AGE18PLUS_FEM', 'AGE1544_TOT',
       'AGE1544_MALE', 'AGE1544_FEM', 'AGE2544_TOT', 'AGE2544_MALE',
       'AGE2544_FEM', 'AGE4564_TOT', 'AGE4564_MALE', 'AGE4564_FEM',
       'AGE65PLUS_TOT', 'AGE65PLUS_MALE', 'AGE65PLUS_FEM', 'AGE04_TOT',
       'AGE04_MALE', 'AGE04_FEM', 'AGE59_TOT', 'AGE59_MALE', 'AGE59_FEM',
       'AGE1014_TOT', 'AGE1014_MALE', 'AGE1014_FEM', 'AGE1519_TOT',
       'AGE1519_MALE', 'AGE1519_FEM', 'AGE2024_TOT', 'AGE2024_MALE',
       'AGE2024_FEM', 'AGE2529_TOT', 'AGE2529_MALE', 'AGE2529_FEM',
       'AGE3034_TOT', 'AGE3034_MALE', 'AGE3034_FEM', 'AGE3539_TOT',
   

This dataframe has 96 variables! Way too much information to take in as is. These are the columns of interest after looking at the [file layout](https://www2.census.gov/programs-surveys/popest/technical-documentation/file-layouts/2010-2019/cc-est2019-agesex.pdf) document included in the documentation

* COUNTY County FIPS code
* CTYNAME County name
* YEAR Year
* POPESTIMATE Total population
* POPEST_MALE Male population
* POPEST_FEM Female population

* UNDER5_TOT Total population under 5 years
* AGE513_TOT Total population age 5 to 13
* AGE1417_TOT Total population age 14 to 17
* AGE1824_TOT Total population age 18 to 24
* AGE18PLUS_TOT Total population age 18 years and over
* AGE18PLUS_MALE Male population age 18 years and over
* AGE18PLUS_FEM Female population age 18 years and over
* AGE1544_TOT Total population age 15 to 44
* AGE65PLUS_TOT Total population age 65 years and over
* AGE2529_TOT Total population age 25 to 29


The key for the YEAR variable to be used: 12 = 7/1/2019 population estimate


In this source, we learn that **population estimate** = population base + births - deaths + migration


In [34]:
county_pop_by_characteristics_age_sex_race_hispanic = pd.read_csv('./data/county_population_by_characteristics_2010-2019_age_sex_race_hispanic-origin.csv')

In [35]:
county_pop_by_characteristics_age_sex_race_hispanic.columns

Index(['SUMLEV', 'STATE', 'COUNTY', 'STNAME', 'CTYNAME', 'YEAR', 'AGEGRP',
       'TOT_POP', 'TOT_MALE', 'TOT_FEMALE', 'WA_MALE', 'WA_FEMALE', 'BA_MALE',
       'BA_FEMALE', 'IA_MALE', 'IA_FEMALE', 'AA_MALE', 'AA_FEMALE', 'NA_MALE',
       'NA_FEMALE', 'TOM_MALE', 'TOM_FEMALE', 'WAC_MALE', 'WAC_FEMALE',
       'BAC_MALE', 'BAC_FEMALE', 'IAC_MALE', 'IAC_FEMALE', 'AAC_MALE',
       'AAC_FEMALE', 'NAC_MALE', 'NAC_FEMALE', 'NH_MALE', 'NH_FEMALE',
       'NHWA_MALE', 'NHWA_FEMALE', 'NHBA_MALE', 'NHBA_FEMALE', 'NHIA_MALE',
       'NHIA_FEMALE', 'NHAA_MALE', 'NHAA_FEMALE', 'NHNA_MALE', 'NHNA_FEMALE',
       'NHTOM_MALE', 'NHTOM_FEMALE', 'NHWAC_MALE', 'NHWAC_FEMALE',
       'NHBAC_MALE', 'NHBAC_FEMALE', 'NHIAC_MALE', 'NHIAC_FEMALE',
       'NHAAC_MALE', 'NHAAC_FEMALE', 'NHNAC_MALE', 'NHNAC_FEMALE', 'H_MALE',
       'H_FEMALE', 'HWA_MALE', 'HWA_FEMALE', 'HBA_MALE', 'HBA_FEMALE',
       'HIA_MALE', 'HIA_FEMALE', 'HAA_MALE', 'HAA_FEMALE', 'HNA_MALE',
       'HNA_FEMALE', 'HTOM_MALE', 'HTOM_FEMALE

In [36]:
len(county_pop_by_characteristics_age_sex_race_hispanic.columns)

80

In [37]:
county_pop_by_characteristics_age_sex_race_hispanic.iloc[0]

SUMLEV                    50
STATE                     36
COUNTY                     1
STNAME              New York
CTYNAME        Albany County
                   ...      
HIAC_FEMALE              410
HAAC_MALE                139
HAAC_FEMALE              141
HNAC_MALE                 41
HNAC_FEMALE               41
Name: 0, Length: 80, dtype: object

This dataset has 80 columns. Below are the columms of interest after review of [file layout](https://www2.census.gov/programs-surveys/popest/technical-documentation/file-layouts/2010-2019/cc-est2019-alldata.pdf) document included in data source.

* COUNTY FIPS
* CTYNAME County Name
* YEAR year (key: 12 = 7/1/2019 population estimate, last date)
* AGEGRP age group (key: 0 is total)
* TOT_POP Total Population
* NH_MALE Not Hispanic male population
* NH_FEMALE Not Hispanic female population
* WA_MALE White alone male population
* WA_FEMALE White alone female population
* BA_MALE Black or African American alone male population
* BA_FEMALE Black or African American alone female population
* IA_MALE  American Indian and Alaska Native alone male population
* IA_FEMALE American Indian and Alaska Native alone female population
* AA_MALE Asian alone male population
* AA_FEMALE Asian alone female population
* NA_MALE Native Hawaiian and Other Pacific Islander alone male population
* NA_FEMALE Native Hawaiian and Other Pacific Islander alone female population
* TOM_MALE Two or More Races male population
* TOM_FEMALE Two or More Races female population
* H_MALE Hispanic male population
* H_FEMALE Hispanic female population

So far, all data in population in integers. To fairly compare counties, we must normalize data.

In [38]:
# county size - to normalize these population fields
county_size = pd.read_csv('./data/ny_land_size_county.csv')

In [39]:
county_size.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 2 columns):
County          62 non-null object
Square Miles    62 non-null float64
dtypes: float64(1), object(1)
memory usage: 1.1+ KB


In [40]:
county_size.head(1)

County  Square Miles
0  Bronx         42.03

Note, county_size df has county as a string and not FIPS code.

In [41]:
poverty = pd.read_csv('./data/ny_county_level_poverty.csv')

In [42]:
poverty.head(4)

FIPS      Name  Unnamed: 2  RUC Code  Percent_Pop  Lower Bound  \
0  36000  New York         NaN       NaN         13.1         12.9   
1  36001    Albany         NaN       2.0         11.7         10.2   
2  36003  Allegany         NaN       7.0         17.9         15.0   
3  36005     Bronx         NaN       1.0         26.2         24.9   

   Upper Bound  Percent_Children  Lower Bound.1  Upper Bound.1  
0         13.3              18.2           17.7           18.7  
1         13.2              16.0           13.1           18.9  
2         20.8              26.8           21.2           32.4  
3         27.5              36.5           33.8           39.2

In [43]:
poverty.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63 entries, 0 to 62
Data columns (total 10 columns):
FIPS                63 non-null int64
Name                63 non-null object
Unnamed: 2          0 non-null float64
RUC Code            62 non-null float64
Percent_Pop         63 non-null float64
Lower Bound         63 non-null float64
Upper Bound         63 non-null float64
Percent_Children    63 non-null float64
Lower Bound.1       63 non-null float64
Upper Bound.1       63 non-null float64
dtypes: float64(8), int64(1), object(1)
memory usage: 5.0+ KB


In [44]:
#Why 63 rows, only 62 counties? 
poverty['Name'].nunique()

62

In [45]:
poverty['Name'].value_counts().head()

New York     2
Genesee      1
Ulster       1
Schoharie    1
Erie         1
Name: Name, dtype: int64

In [46]:
#let's look at those two rows
poverty.loc[poverty['Name']=='New York']

FIPS      Name  Unnamed: 2  RUC Code  Percent_Pop  Lower Bound  \
0   36000  New York         NaN       NaN         13.1         12.9   
31  36061  New York         NaN       1.0         14.1         13.1   

    Upper Bound  Percent_Children  Lower Bound.1  Upper Bound.1  
0          13.3              18.2           17.7           18.7  
31         15.1              17.3           13.9           20.7

Note, 63 counties are one line for "New York" most likely combining the 4 NYC counties.New York Listed Twice. The first one with FIPS 36000 is not a real FIPS code. Assumingly, this is extra and supposed to represent a line for all NYC counties combined which I have seen often in other documents.

In [47]:
unemployment_income = pd.read_csv('./data/ny_county_level_unemployment_median_household_income.csv')

In [48]:
unemployment_income.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63 entries, 0 to 62
Data columns (total 13 columns):
FIPS                              63 non-null int64
Name                              63 non-null object
2011 Unemployment Rate            63 non-null float64
2012 Unemployment Rate            63 non-null float64
2013 Unemployment Rate            63 non-null float64
2014 Unemployment Rate            63 non-null float64
2015 Unemployment Rate            63 non-null float64
2016 Unemployment Rate            63 non-null float64
2017 Unemployment Rate            63 non-null float64
2018 Unemployment Rate            63 non-null float64
2019 Unemployment Rate            63 non-null float64
Median Household Income (2019)    63 non-null object
% of State Median HH Income       63 non-null object
dtypes: float64(9), int64(1), object(3)
memory usage: 6.5+ KB


In [49]:
unemployment_income.head(3)

FIPS                 Name  2011 Unemployment Rate  2012 Unemployment Rate  \
0  36000             New York                     8.3                     8.5   
1  36001    Albany County, NY                     6.9                     7.1   
2  36003  Allegany County, NY                     8.9                     8.4   

   2013 Unemployment Rate  2014 Unemployment Rate  2015 Unemployment Rate  \
0                     7.7                     6.3                     5.3   
1                     6.1                     4.9                     4.3   
2                     7.5                     6.2                     6.5   

   2016 Unemployment Rate  2017 Unemployment Rate  2018 Unemployment Rate  \
0                     4.9                     4.7                     4.1   
1                     4.1                     4.2                     3.7   
2                     6.3                     6.6                     5.6   

   2019 Unemployment Rate Median Household Income (2019)  \
0                     4.0                        $72,038   
1                     3.6                        $69,408   
2                     5.5                        $49,411   

  % of State Median HH Income  
0                      100.0%  
1                       96.3%  
2                       68.6%

Will only need 2019 unemployment rate.

In [50]:
# 63 like the previous df. As same source, assume it is for the same reason
unemployment_income['Name'].unique()

array(['New York', 'Albany County, NY', 'Allegany County, NY',
       'Bronx County, NY', 'Broome County, NY', 'Cattaraugus County, NY',
       'Cayuga County, NY', 'Chautauqua County, NY', 'Chemung County, NY',
       'Chenango County, NY', 'Clinton County, NY', 'Columbia County, NY',
       'Cortland County, NY', 'Delaware County, NY',
       'Dutchess County, NY', 'Erie County, NY', 'Essex County, NY',
       'Franklin County, NY', 'Fulton County, NY', 'Genesee County, NY',
       'Greene County, NY', 'Hamilton County, NY', 'Herkimer County, NY',
       'Jefferson County, NY', 'Kings County, NY', 'Lewis County, NY',
       'Livingston County, NY', 'Madison County, NY', 'Monroe County, NY',
       'Montgomery County, NY', 'Nassau County, NY',
       'New York County, NY', 'Niagara County, NY', 'Oneida County, NY',
       'Onondaga County, NY', 'Ontario County, NY', 'Orange County, NY',
       'Orleans County, NY', 'Oswego County, NY', 'Otsego County, NY',
       'Putnam County, NY', 

New York and New York County

In [51]:
unemployment_income.head()

FIPS                 Name  2011 Unemployment Rate  2012 Unemployment Rate  \
0  36000             New York                     8.3                     8.5   
1  36001    Albany County, NY                     6.9                     7.1   
2  36003  Allegany County, NY                     8.9                     8.4   
3  36005     Bronx County, NY                    11.9                    12.4   
4  36007    Broome County, NY                     8.6                     8.7   

   2013 Unemployment Rate  2014 Unemployment Rate  2015 Unemployment Rate  \
0                     7.7                     6.3                     5.3   
1                     6.1                     4.9                     4.3   
2                     7.5                     6.2                     6.5   
3                    11.8                     9.8                     7.8   
4                     7.8                     6.6                     6.0   

   2016 Unemployment Rate  2017 Unemployment Rate  2018 Unemployment Rate  \
0                     4.9                     4.7                     4.1   
1                     4.1                     4.2                     3.7   
2                     6.3                     6.6                     5.6   
3                     7.1                     6.3                     5.8   
4                     5.4                     5.5                     4.9   

   2019 Unemployment Rate Median Household Income (2019)  \
0                     4.0                        $72,038   
1                     3.6                        $69,408   
2                     5.5                        $49,411   
3                     5.4                        $41,470   
4                     4.7                        $52,179   

  % of State Median HH Income  
0                      100.0%  
1                       96.3%  
2                       68.6%  
3                       57.6%  
4                       72.4%

removing 0 as it has the 36000 FIPS code

In [52]:
hospitals = pd.read_csv('./data/hospitals.csv')

In [53]:
hospitals.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7596 entries, 0 to 7595
Data columns (total 34 columns):
X             7596 non-null float64
Y             7596 non-null float64
OBJECTID      7596 non-null int64
ID            7596 non-null int64
NAME          7596 non-null object
ADDRESS       7596 non-null object
CITY          7596 non-null object
STATE         7596 non-null object
ZIP           7596 non-null int64
ZIP4          7596 non-null object
TELEPHONE     7596 non-null object
TYPE          7596 non-null object
STATUS        7596 non-null object
POPULATION    7596 non-null int64
COUNTY        7596 non-null object
COUNTYFIPS    7596 non-null object
COUNTRY       7596 non-null object
LATITUDE      7596 non-null float64
LONGITUDE     7596 non-null float64
NAICS_CODE    7596 non-null int64
NAICS_DESC    7596 non-null object
SOURCE        7596 non-null object
SOURCEDATE    7596 non-null object
VAL_METHOD    7596 non-null object
VAL_DATE      7596 non-null object
WEBSITE       7596 

Pending - Filter only NY and do count per county

## 3) Data PreProcessing <a class="anchor" id="datacleaning"></a>

**Covid Deaths**

First, we need to restructure this dataset

In [54]:
covid_daily.columns

Index(['countyFIPS', 'County Name', 'State', 'stateFIPS', '1/22/20', '1/23/20',
       '1/24/20', '1/25/20', '1/26/20', '1/27/20',
       ...
       '12/30/20', '12/31/20', '1/1/21', '1/2/21', '1/3/21', '1/4/21',
       '1/5/21', '1/6/21', '1/7/21', '1/8/21'],
      dtype='object', length=357)

In [55]:
covid_daily = pd.melt(covid_daily, id_vars=['countyFIPS', 'County Name', 'State', 'stateFIPS'],var_name='Date', value_name='Deaths')
covid_daily.head()

countyFIPS            County Name State  stateFIPS     Date  Deaths
0           0  Statewide Unallocated    AL          1  1/22/20       0
1        1001         Autauga County    AL          1  1/22/20       0
2        1003         Baldwin County    AL          1  1/22/20       0
3        1005         Barbour County    AL          1  1/22/20       0
4        1007            Bibb County    AL          1  1/22/20       0

Now that it is in an ingestible format. Let's look at further processing needed.

In [56]:
covid_daily.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1127835 entries, 0 to 1127834
Data columns (total 6 columns):
countyFIPS     1127835 non-null int64
County Name    1127835 non-null object
State          1127835 non-null object
stateFIPS      1127835 non-null int64
Date           1127835 non-null object
Deaths         1127835 non-null int64
dtypes: int64(3), object(3)
memory usage: 51.6+ MB


In [57]:
#Change Date to date field
covid_daily['Date'] = pd.to_datetime(covid_daily['Date'])

In [58]:
#confirm change to date
covid_daily.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1127835 entries, 0 to 1127834
Data columns (total 6 columns):
countyFIPS     1127835 non-null int64
County Name    1127835 non-null object
State          1127835 non-null object
stateFIPS      1127835 non-null int64
Date           1127835 non-null datetime64[ns]
Deaths         1127835 non-null int64
dtypes: datetime64[ns](1), int64(3), object(2)
memory usage: 51.6+ MB


In [59]:
# What date range is included?
print(covid_daily['Date'].min(),' - ', covid_daily['Date'].max())

2020-01-22 00:00:00  -  2021-01-08 00:00:00


We have Covid Deaths data from 1/22 to 1/8/21

In [60]:
#Now, is the data just for NY?
covid_daily['State'].nunique()

51

No, this data apparently has all states. Let's change to just NY

In [61]:
#Confirm it is state 'NY'
covid_daily['State'].unique()

array(['AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'DC', 'FL', 'GA',
       'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA',
       'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY',
       'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX',
       'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY'], dtype=object)

In [62]:
covid_daily = covid_daily.loc[covid_daily['State']=='NY']

In [63]:
#confirm only 'NY'
covid_daily['State'].unique()

array(['NY'], dtype=object)

In [64]:
#Confirm, not 0
len(covid_daily)

22592

In [65]:
#how many counties represented?
covid_daily['County Name'].nunique()

64

New York only has 62 counties, what are extra 2?

In [66]:
#let's explore
covid_daily['County Name'].unique()

array(['Statewide Unallocated', 'New York City Unallocated/Probable',
       'Albany County', 'Allegany County', 'Bronx County',
       'Broome County', 'Cattaraugus County', 'Cayuga County',
       'Chautauqua County', 'Chemung County', 'Chenango County',
       'Clinton County', 'Columbia County', 'Cortland County',
       'Delaware County', 'Dutchess County', 'Erie County',
       'Essex County', 'Franklin County', 'Fulton County',
       'Genesee County', 'Greene County', 'Hamilton County',
       'Herkimer County', 'Jefferson County', 'Kings County',
       'Lewis County', 'Livingston County', 'Madison County',
       'Monroe County', 'Montgomery County', 'Nassau County',
       'New York County', 'Niagara County', 'Oneida County',
       'Onondaga County', 'Ontario County', 'Orange County',
       'Orleans County', 'Oswego County', 'Otsego County',
       'Putnam County', 'Queens County', 'Rensselaer County',
       'Richmond County', 'Rockland County', 'St. Lawrence County',
   

In [67]:
covid_daily.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 22592 entries, 1861 to 1126564
Data columns (total 6 columns):
countyFIPS     22592 non-null int64
County Name    22592 non-null object
State          22592 non-null object
stateFIPS      22592 non-null int64
Date           22592 non-null datetime64[ns]
Deaths         22592 non-null int64
dtypes: datetime64[ns](1), int64(3), object(2)
memory usage: 1.2+ MB


The two extra are "Statewide Unallocated" and "New York City Unallocated / Probable". Can these be dropped? What % deaths is that?

In [68]:
covid_daily.loc[covid_daily['County Name'] == 'Statewide Unallocated']

countyFIPS            County Name State  stateFIPS       Date  Deaths
1861              0  Statewide Unallocated    NY         36 2020-01-22       0
5056              0  Statewide Unallocated    NY         36 2020-01-23       0
8251              0  Statewide Unallocated    NY         36 2020-01-24       0
11446             0  Statewide Unallocated    NY         36 2020-01-25       0
14641             0  Statewide Unallocated    NY         36 2020-01-26       0
...             ...                    ...   ...        ...        ...     ...
1113721           0  Statewide Unallocated    NY         36 2021-01-04     156
1116916           0  Statewide Unallocated    NY         36 2021-01-05     157
1120111           0  Statewide Unallocated    NY         36 2021-01-06     157
1123306           0  Statewide Unallocated    NY         36 2021-01-07     158
1126501           0  Statewide Unallocated    NY         36 2021-01-08     158

[353 rows x 6 columns]

In [69]:
#Statewide Unallocated
covid_daily.loc[covid_daily['County Name'] == 'Statewide Unallocated'].sort_values(by='Deaths', ascending=False).head(1)

countyFIPS            County Name State  stateFIPS       Date  Deaths
231901           0  Statewide Unallocated    NY         36 2020-04-03     559

In [70]:
covid_daily['Date'].max()

Timestamp('2021-01-08 00:00:00')

In [71]:
#Do we have 64 measures for 1/8/21?
len(covid_daily.loc[covid_daily['Date'] == '2021-01-08']) == 64

True

In [72]:
#How many deaths does Statewide Unallocated make up of total deaths?
total_covid_deaths = covid_daily.loc[covid_daily['Date'] == '2021-01-08']['Deaths'].sum()
559/total_covid_deaths

0.014331863398625782

Statewide unallocated represents less 2% of the deaths and too big of an area. This will be dropped

In [73]:
#New York City Unallocated/Probable
covid_daily.loc[covid_daily['County Name'] == 'New York City Unallocated/Probable'].sort_values(by='Deaths', ascending=False).head(1)

countyFIPS                         County Name State  stateFIPS  \
263852           1  New York City Unallocated/Probable    NY         36   

             Date  Deaths  
263852 2020-04-13    2853

In [74]:
2853/total_covid_deaths

0.07314634396472157

NYC deaths represent a much larger portion at 7% of the total deaths. Although we can allocate by borough, we can't allocate by date and this data will be joined to other datasets by county code. Hence, we will drop these too. 

In [75]:
#slicing by only counties that are not any of the two in question
covid_daily = covid_daily.loc[covid_daily['County Name'].isin(['Statewide Unallocated', 'New York City Unallocated/Probable']) == False]

In [76]:
#Are there 62 counties now?
covid_daily['County Name'].nunique() == 62

True

In [77]:
covid_daily.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 21886 entries, 1863 to 1126564
Data columns (total 6 columns):
countyFIPS     21886 non-null int64
County Name    21886 non-null object
State          21886 non-null object
stateFIPS      21886 non-null int64
Date           21886 non-null datetime64[ns]
Deaths         21886 non-null int64
dtypes: datetime64[ns](1), int64(3), object(2)
memory usage: 1.2+ MB


In [78]:
#Do we have 62 observations per date?
covid_daily['Date'].value_counts()

2020-10-28    62
2020-02-12    62
2020-10-16    62
2020-03-15    62
2020-06-24    62
              ..
2020-05-04    62
2020-08-13    62
2020-11-22    62
2020-04-21    62
2020-03-27    62
Name: Date, Length: 353, dtype: int64

Yes, we have death values on all counties per date! This dataset is ready.

**Air Quality**

In [79]:
air_2010_2020.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133889 entries, 0 to 133888
Data columns (total 21 columns):
Date                              133889 non-null object
Source                            133889 non-null object
Site ID                           133889 non-null int64
POC                               133889 non-null int64
Daily Mean PM2.5 Concentration    133889 non-null float64
UNITS                             133889 non-null object
DAILY_AQI_VALUE                   133889 non-null int64
Site Name                         133889 non-null object
DAILY_OBS_COUNT                   133889 non-null int64
PERCENT_COMPLETE                  133889 non-null float64
AQS_PARAMETER_CODE                133889 non-null int64
AQS_PARAMETER_DESC                133889 non-null object
CBSA_CODE                         129652 non-null float64
CBSA_NAME                         129652 non-null object
STATE_CODE                        133889 non-null int64
STATE                             133

In [80]:
#update date
air_2010_2020['Date'] = pd.to_datetime(air_2010_2020['Date'])

In [81]:
#confirm date is not a datetime
air_2010_2020.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133889 entries, 0 to 133888
Data columns (total 21 columns):
Date                              133889 non-null datetime64[ns]
Source                            133889 non-null object
Site ID                           133889 non-null int64
POC                               133889 non-null int64
Daily Mean PM2.5 Concentration    133889 non-null float64
UNITS                             133889 non-null object
DAILY_AQI_VALUE                   133889 non-null int64
Site Name                         133889 non-null object
DAILY_OBS_COUNT                   133889 non-null int64
PERCENT_COMPLETE                  133889 non-null float64
AQS_PARAMETER_CODE                133889 non-null int64
AQS_PARAMETER_DESC                133889 non-null object
CBSA_CODE                         129652 non-null float64
CBSA_NAME                         129652 non-null object
STATE_CODE                        133889 non-null int64
STATE                        

In [82]:
air_2010_2020.columns

Index(['Date', 'Source', 'Site ID', 'POC', 'Daily Mean PM2.5 Concentration',
       'UNITS', 'DAILY_AQI_VALUE', 'Site Name', 'DAILY_OBS_COUNT',
       'PERCENT_COMPLETE', 'AQS_PARAMETER_CODE', 'AQS_PARAMETER_DESC',
       'CBSA_CODE', 'CBSA_NAME', 'STATE_CODE', 'STATE', 'COUNTY_CODE',
       'COUNTY', 'SITE_LATITUDE', 'SITE_LONGITUDE', 'year'],
      dtype='object')

In [83]:
#Drop columns 100% won't be used
air_2010_2020 = air_2010_2020[['Date', 'Site ID', 'Daily Mean PM2.5 Concentration',
       'UNITS', 'DAILY_AQI_VALUE', 'Site Name', 'AQS_PARAMETER_CODE', 'AQS_PARAMETER_DESC','COUNTY_CODE',
       'COUNTY', 'SITE_LATITUDE', 'SITE_LONGITUDE', 'year']]

In [84]:
air_2010_2020.head(1)

Date    Site ID  Daily Mean PM2.5 Concentration     UNITS  \
0 2010-01-01  360010005                            22.5  ug/m3 LC   

   DAILY_AQI_VALUE                  Site Name  AQS_PARAMETER_CODE  \
0               73  ALBANY COUNTY HEALTH DEPT               88101   

         AQS_PARAMETER_DESC  COUNTY_CODE  COUNTY  SITE_LATITUDE  \
0  PM2.5 - Local Conditions            1  Albany       42.64225   

   SITE_LONGITUDE  year  
0       -73.75464  2010

**County Demographics**

* Population by Characteristics (Age Group and Sex)
* Population by Characteristics (Age, Sex, Race, Hispanic Origin)
* Size
* Poverty
* Unemployment and Household Income
* Hospitals

*Population by Characteristics (Age Group and Sex)*

In [85]:
# COUNTY POP BY CHARACTERISTICS AGE DATA
county_pop_by_characteristics_age_sex.columns

Index(['SUMLEV', 'STATE', 'COUNTY', 'STNAME', 'CTYNAME', 'YEAR', 'POPESTIMATE',
       'POPEST_MALE', 'POPEST_FEM', 'UNDER5_TOT', 'UNDER5_MALE', 'UNDER5_FEM',
       'AGE513_TOT', 'AGE513_MALE', 'AGE513_FEM', 'AGE1417_TOT',
       'AGE1417_MALE', 'AGE1417_FEM', 'AGE1824_TOT', 'AGE1824_MALE',
       'AGE1824_FEM', 'AGE16PLUS_TOT', 'AGE16PLUS_MALE', 'AGE16PLUS_FEM',
       'AGE18PLUS_TOT', 'AGE18PLUS_MALE', 'AGE18PLUS_FEM', 'AGE1544_TOT',
       'AGE1544_MALE', 'AGE1544_FEM', 'AGE2544_TOT', 'AGE2544_MALE',
       'AGE2544_FEM', 'AGE4564_TOT', 'AGE4564_MALE', 'AGE4564_FEM',
       'AGE65PLUS_TOT', 'AGE65PLUS_MALE', 'AGE65PLUS_FEM', 'AGE04_TOT',
       'AGE04_MALE', 'AGE04_FEM', 'AGE59_TOT', 'AGE59_MALE', 'AGE59_FEM',
       'AGE1014_TOT', 'AGE1014_MALE', 'AGE1014_FEM', 'AGE1519_TOT',
       'AGE1519_MALE', 'AGE1519_FEM', 'AGE2024_TOT', 'AGE2024_MALE',
       'AGE2024_FEM', 'AGE2529_TOT', 'AGE2529_MALE', 'AGE2529_FEM',
       'AGE3034_TOT', 'AGE3034_MALE', 'AGE3034_FEM', 'AGE3539_TOT',
   

In [86]:
# First extract only 2019 data
county_pop_by_characteristics_age_sex['YEAR'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int64)

Only using year 12 which is the 2019 estimate, when possible I will get 2019 data (last year pre-covid).

In [87]:
# confirm only NY
county_pop_by_characteristics_age_sex['STNAME'].unique()

array(['New York'], dtype=object)

In [88]:
county_pop_by_characteristics_age_sex = county_pop_by_characteristics_age_sex.loc[county_pop_by_characteristics_age_sex['YEAR']==12]

In [89]:
county_pop_by_characteristics_age_sex['YEAR'].unique()

array([12], dtype=int64)

In [90]:
#Now only keep columns to be be looked at further
county_pop_by_characteristics_age_sex = county_pop_by_characteristics_age_sex[['COUNTY', 'CTYNAME', 'POPESTIMATE', 'POPEST_MALE', 'POPEST_FEM', 'UNDER5_TOT', 'AGE513_TOT', 'AGE1417_TOT', 'AGE1824_TOT', 'AGE18PLUS_TOT', 'AGE18PLUS_MALE', 'AGE18PLUS_FEM', 'AGE1544_TOT', 'AGE65PLUS_TOT', 'AGE2529_TOT']]

In [91]:
county_pop_by_characteristics_age_sex.head()

COUNTY             CTYNAME  POPESTIMATE  POPEST_MALE  POPEST_FEM  \
11       1       Albany County       305506       147818      157688   
23       3     Allegany County        46091        23418       22673   
35       5        Bronx County      1418207       669548      748659   
47       7       Broome County       190488        93845       96643   
59       9  Cattaraugus County        76117        37853       38264   

    UNDER5_TOT  AGE513_TOT  AGE1417_TOT  AGE1824_TOT  AGE18PLUS_TOT  \
11       15204       27656        12905        44050         249741   
23        2424        4589         2261         6687          36817   
35      100199      173858        74606       137701        1069544   
47        9886       18366         8553        27003         153683   
59        4160        8489         3987         6862          59481   

    AGE18PLUS_MALE  AGE18PLUS_FEM  AGE1544_TOT  AGE65PLUS_TOT  AGE2529_TOT  
11          119344         130397       130232          53272        21533  
23           18575          18242        17809           9055         2248  
35          491544         578000       600560         188766       119696  
47           74712          78971        74863          36980        11418  
59           29355          30126        26527          15022         4170

In [92]:
len(county_pop_by_characteristics_age_sex)

62

In [93]:
county_pop_by_characteristics_age_sex.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 62 entries, 11 to 743
Data columns (total 15 columns):
COUNTY            62 non-null int64
CTYNAME           62 non-null object
POPESTIMATE       62 non-null int64
POPEST_MALE       62 non-null int64
POPEST_FEM        62 non-null int64
UNDER5_TOT        62 non-null int64
AGE513_TOT        62 non-null int64
AGE1417_TOT       62 non-null int64
AGE1824_TOT       62 non-null int64
AGE18PLUS_TOT     62 non-null int64
AGE18PLUS_MALE    62 non-null int64
AGE18PLUS_FEM     62 non-null int64
AGE1544_TOT       62 non-null int64
AGE65PLUS_TOT     62 non-null int64
AGE2529_TOT       62 non-null int64
dtypes: int64(14), object(1)
memory usage: 7.8+ KB


No nulls. All variables are correct data type. Now, one line per county. Closer to the county dataframe we need

"County" = FIPS Code.

*Population by Characteristics (Age, Sex, Race, Hispanic Origin)*

In [94]:
county_pop_by_characteristics_age_sex_race_hispanic.columns

Index(['SUMLEV', 'STATE', 'COUNTY', 'STNAME', 'CTYNAME', 'YEAR', 'AGEGRP',
       'TOT_POP', 'TOT_MALE', 'TOT_FEMALE', 'WA_MALE', 'WA_FEMALE', 'BA_MALE',
       'BA_FEMALE', 'IA_MALE', 'IA_FEMALE', 'AA_MALE', 'AA_FEMALE', 'NA_MALE',
       'NA_FEMALE', 'TOM_MALE', 'TOM_FEMALE', 'WAC_MALE', 'WAC_FEMALE',
       'BAC_MALE', 'BAC_FEMALE', 'IAC_MALE', 'IAC_FEMALE', 'AAC_MALE',
       'AAC_FEMALE', 'NAC_MALE', 'NAC_FEMALE', 'NH_MALE', 'NH_FEMALE',
       'NHWA_MALE', 'NHWA_FEMALE', 'NHBA_MALE', 'NHBA_FEMALE', 'NHIA_MALE',
       'NHIA_FEMALE', 'NHAA_MALE', 'NHAA_FEMALE', 'NHNA_MALE', 'NHNA_FEMALE',
       'NHTOM_MALE', 'NHTOM_FEMALE', 'NHWAC_MALE', 'NHWAC_FEMALE',
       'NHBAC_MALE', 'NHBAC_FEMALE', 'NHIAC_MALE', 'NHIAC_FEMALE',
       'NHAAC_MALE', 'NHAAC_FEMALE', 'NHNAC_MALE', 'NHNAC_FEMALE', 'H_MALE',
       'H_FEMALE', 'HWA_MALE', 'HWA_FEMALE', 'HBA_MALE', 'HBA_FEMALE',
       'HIA_MALE', 'HIA_FEMALE', 'HAA_MALE', 'HAA_FEMALE', 'HNA_MALE',
       'HNA_FEMALE', 'HTOM_MALE', 'HTOM_FEMALE

In [95]:
county_pop_by_characteristics_age_sex_race_hispanic['YEAR'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int64)

In [96]:
#Filter by Year 12

county_pop_by_characteristics_age_sex_race_hispanic = county_pop_by_characteristics_age_sex_race_hispanic.loc[county_pop_by_characteristics_age_sex_race_hispanic['YEAR']==12]

In [97]:
county_pop_by_characteristics_age_sex_race_hispanic['YEAR'].unique()

array([12], dtype=int64)

In [98]:
# Filter by Age Group - Total
county_pop_by_characteristics_age_sex_race_hispanic['AGEGRP'].unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18], dtype=int64)

In [99]:
county_pop_by_characteristics_age_sex_race_hispanic = county_pop_by_characteristics_age_sex_race_hispanic.loc[county_pop_by_characteristics_age_sex_race_hispanic['AGEGRP']==0]

In [100]:
# Filter by Age Group - Total
county_pop_by_characteristics_age_sex_race_hispanic['AGEGRP'].unique()

array([0], dtype=int64)

In [101]:
#Is it 62 rows? 1 per county
len(county_pop_by_characteristics_age_sex_race_hispanic) == 62

True

In [102]:
#only keep certain columns
keep = ['COUNTY','CTYNAME', 'TOT_POP', 'NH_MALE', 'NH_FEMALE', 'NHWA_MALE', 'NHWA_FEMALE', 'WA_MALE', 'WA_FEMALE', 'BA_MALE','BA_FEMALE',  
      'IA_MALE', 'IA_FEMALE', 'AA_MALE', 'AA_FEMALE', 'NA_MALE', 'NA_FEMALE', 'TOM_MALE', 'TOM_FEMALE', 
        'H_MALE', 'H_FEMALE']

county_pop_by_characteristics_age_sex_race_hispanic = county_pop_by_characteristics_age_sex_race_hispanic[keep]

In [103]:
county_pop_by_characteristics_age_sex_race_hispanic.head(1)

COUNTY        CTYNAME  TOT_POP  NH_MALE  NH_FEMALE  NHWA_MALE  \
209       1  Albany County   305506   138525     147879     105918   

     NHWA_FEMALE  WA_MALE  WA_FEMALE  BA_MALE  ...  IA_MALE  IA_FEMALE  \
209       112727   112279     119259    20431  ...      456        474   

     AA_MALE  AA_FEMALE  NA_MALE  NA_FEMALE  TOM_MALE  TOM_FEMALE  H_MALE  \
209    10189      10696      101        101      4362        4493    9293   

     H_FEMALE  
209      9809  

[1 rows x 21 columns]

In [104]:
county_pop_by_characteristics_age_sex_race_hispanic.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 62 entries, 209 to 14117
Data columns (total 21 columns):
COUNTY         62 non-null int64
CTYNAME        62 non-null object
TOT_POP        62 non-null int64
NH_MALE        62 non-null int64
NH_FEMALE      62 non-null int64
NHWA_MALE      62 non-null int64
NHWA_FEMALE    62 non-null int64
WA_MALE        62 non-null int64
WA_FEMALE      62 non-null int64
BA_MALE        62 non-null int64
BA_FEMALE      62 non-null int64
IA_MALE        62 non-null int64
IA_FEMALE      62 non-null int64
AA_MALE        62 non-null int64
AA_FEMALE      62 non-null int64
NA_MALE        62 non-null int64
NA_FEMALE      62 non-null int64
TOM_MALE       62 non-null int64
TOM_FEMALE     62 non-null int64
H_MALE         62 non-null int64
H_FEMALE       62 non-null int64
dtypes: int64(20), object(1)
memory usage: 10.7+ KB


No nulls and correct data types.

In [105]:
#New York rows in poverty
poverty.loc[poverty['Name']=='New York']

FIPS      Name  Unnamed: 2  RUC Code  Percent_Pop  Lower Bound  \
0   36000  New York         NaN       NaN         13.1         12.9   
31  36061  New York         NaN       1.0         14.1         13.1   

    Upper Bound  Percent_Children  Lower Bound.1  Upper Bound.1  
0          13.3              18.2           17.7           18.7  
31         15.1              17.3           13.9           20.7

In [106]:
#Drop extra row
poverty.drop(poverty.index[0], inplace=True)

In [107]:
#New York rows in poverty - only 1 row now
poverty.loc[poverty['Name']=='New York']

FIPS      Name  Unnamed: 2  RUC Code  Percent_Pop  Lower Bound  \
31  36061  New York         NaN       1.0         14.1         13.1   

    Upper Bound  Percent_Children  Lower Bound.1  Upper Bound.1  
31         15.1              17.3           13.9           20.7

In [108]:
#all should be 62
poverty.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 62 entries, 1 to 62
Data columns (total 10 columns):
FIPS                62 non-null int64
Name                62 non-null object
Unnamed: 2          0 non-null float64
RUC Code            62 non-null float64
Percent_Pop         62 non-null float64
Lower Bound         62 non-null float64
Upper Bound         62 non-null float64
Percent_Children    62 non-null float64
Lower Bound.1       62 non-null float64
Upper Bound.1       62 non-null float64
dtypes: float64(8), int64(1), object(1)
memory usage: 5.3+ KB


In [109]:
# drop empty columns
del poverty['Unnamed: 2']

In [110]:
# confirm drop
poverty.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 62 entries, 1 to 62
Data columns (total 9 columns):
FIPS                62 non-null int64
Name                62 non-null object
RUC Code            62 non-null float64
Percent_Pop         62 non-null float64
Lower Bound         62 non-null float64
Upper Bound         62 non-null float64
Percent_Children    62 non-null float64
Lower Bound.1       62 non-null float64
Upper Bound.1       62 non-null float64
dtypes: float64(7), int64(1), object(1)
memory usage: 4.8+ KB


In [111]:
unemployment_income.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63 entries, 0 to 62
Data columns (total 13 columns):
FIPS                              63 non-null int64
Name                              63 non-null object
2011 Unemployment Rate            63 non-null float64
2012 Unemployment Rate            63 non-null float64
2013 Unemployment Rate            63 non-null float64
2014 Unemployment Rate            63 non-null float64
2015 Unemployment Rate            63 non-null float64
2016 Unemployment Rate            63 non-null float64
2017 Unemployment Rate            63 non-null float64
2018 Unemployment Rate            63 non-null float64
2019 Unemployment Rate            63 non-null float64
Median Household Income (2019)    63 non-null object
% of State Median HH Income       63 non-null object
dtypes: float64(9), int64(1), object(3)
memory usage: 6.5+ KB


In [112]:
# only columns needed.
unemployment_income  = unemployment_income[['FIPS', 'Name', '2019 Unemployment Rate', 'Median Household Income (2019)']]

In [113]:
unemployment_income.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63 entries, 0 to 62
Data columns (total 4 columns):
FIPS                              63 non-null int64
Name                              63 non-null object
2019 Unemployment Rate            63 non-null float64
Median Household Income (2019)    63 non-null object
dtypes: float64(1), int64(1), object(2)
memory usage: 2.1+ KB


In [114]:
#Drop extra NY in unemployment_income
unemployment_income.drop(unemployment_income.index[0], inplace=True)

In [115]:
unemployment_income.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 62 entries, 1 to 62
Data columns (total 4 columns):
FIPS                              62 non-null int64
Name                              62 non-null object
2019 Unemployment Rate            62 non-null float64
Median Household Income (2019)    62 non-null object
dtypes: float64(1), int64(1), object(2)
memory usage: 2.4+ KB


In [116]:
# confirm index 0 dropped
unemployment_income.head(3)

FIPS                 Name  2019 Unemployment Rate  \
1  36001    Albany County, NY                     3.6   
2  36003  Allegany County, NY                     5.5   
3  36005     Bronx County, NY                     5.4   

  Median Household Income (2019)  
1                        $69,408  
2                        $49,411  
3                        $41,470

In [117]:
hospitals.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7596 entries, 0 to 7595
Data columns (total 34 columns):
X             7596 non-null float64
Y             7596 non-null float64
OBJECTID      7596 non-null int64
ID            7596 non-null int64
NAME          7596 non-null object
ADDRESS       7596 non-null object
CITY          7596 non-null object
STATE         7596 non-null object
ZIP           7596 non-null int64
ZIP4          7596 non-null object
TELEPHONE     7596 non-null object
TYPE          7596 non-null object
STATUS        7596 non-null object
POPULATION    7596 non-null int64
COUNTY        7596 non-null object
COUNTYFIPS    7596 non-null object
COUNTRY       7596 non-null object
LATITUDE      7596 non-null float64
LONGITUDE     7596 non-null float64
NAICS_CODE    7596 non-null int64
NAICS_DESC    7596 non-null object
SOURCE        7596 non-null object
SOURCEDATE    7596 non-null object
VAL_METHOD    7596 non-null object
VAL_DATE      7596 non-null object
WEBSITE       7596 

In [118]:
hospitals.STATE.unique()

array(['CA', 'TX', 'GA', 'LA', 'IL', 'PR', 'WI', 'RI', 'AR', 'DC', 'FL',
       'MA', 'CT', 'KY', 'IA', 'KS', 'AZ', 'ME', 'MI', 'MN', 'MO', 'ND',
       'IN', 'NV', 'PA', 'MT', 'SC', 'VA', 'OH', 'WA', 'OR', 'NY', 'NH',
       'MD', 'OK', 'WV', 'SD', 'TN', 'AK', 'WY', 'NM', 'ID', 'NE', 'HI',
       'AL', 'NC', 'CO', 'MS', 'NJ', 'UT', 'VT', 'VI', 'DE', 'GU', 'MP',
       'PW', 'AS'], dtype=object)

In [119]:
#only NY
hospitals = hospitals.loc[hospitals['STATE']=='NY']

In [120]:
#confirm change done
hospitals.STATE.unique()

array(['NY'], dtype=object)

In [121]:
# confirm 62 countyFIPS codes
hospitals['COUNTYFIPS'].nunique()

57

It seems some counties dont have hospitals.At this point, unsure if missed or the county really doesn't have a hospital

In [122]:
# Fine one county missing
print(hospitals['COUNTY'].unique())
print('---------')
print(unemployment_income['Name'].unique())

['DUTCHESS' 'ERIE' 'MONROE' 'NASSAU' 'ONONDAGA' 'ORANGE' 'RENSSELAER'
 'ST. LAWRENCE' 'ROCKLAND' 'SARATOGA' 'STEUBEN' 'SUFFOLK' 'ULSTER' 'WAYNE'
 'WESTCHESTER' 'BRONX' 'KINGS' 'NEW YORK' 'QUEENS' 'MONTGOMERY' 'CLINTON'
 'CHAUTAUQUA' 'ONTARIO' 'RICHMOND' 'SULLIVAN' 'CHEMUNG' 'DELAWARE'
 'CATTARAUGUS' 'BROOME' 'CORTLAND' 'ESSEX' 'FULTON' 'FRANKLIN' 'GENESEE'
 'JEFFERSON' 'LEWIS' 'NIAGARA' 'ONEIDA' 'OSWEGO' 'OTSEGO' 'SCHENECTADY'
 'TOMPKINS' 'WARREN' 'ALBANY' 'MADISON' 'ALLEGANY' 'COLUMBIA' 'ORLEANS'
 'CHENANGO' 'CAYUGA' 'HERKIMER' 'PUTNAM' 'SCHOHARIE' 'SCHUYLER' 'YATES'
 'WYOMING' 'LIVINGSTON']
---------
['Albany County, NY' 'Allegany County, NY' 'Bronx County, NY'
 'Broome County, NY' 'Cattaraugus County, NY' 'Cayuga County, NY'
 'Chautauqua County, NY' 'Chemung County, NY' 'Chenango County, NY'
 'Clinton County, NY' 'Columbia County, NY' 'Cortland County, NY'
 'Delaware County, NY' 'Dutchess County, NY' 'Erie County, NY'
 'Essex County, NY' 'Franklin County, NY' 'Fulton County, NY'
 'G

Greene missing. This county is very small so mabe it really doesn't have hospitals. Is there a hospital in Greene County? 

Apparently no. A Google search did not return any hospitals within the county. Hence, I will accept that if a county is not listed, it is because it doesn't have any hospitals.

**Make County df**

In [123]:
#Using poverty as base as the Name is formatted nicely
county = poverty[['FIPS', 'Name']].copy()
county.rename(columns={"Name": "county_name"},inplace=True)
county.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 62 entries, 1 to 62
Data columns (total 2 columns):
FIPS           62 non-null int64
county_name    62 non-null object
dtypes: int64(1), object(1)
memory usage: 1.5+ KB


In [124]:
#Main df with 1 line per county
county.head(3)

FIPS county_name
1  36001      Albany
2  36003    Allegany
3  36005       Bronx

In [125]:
#county_pop_by_characteristics_age_sex
county_pop_by_characteristics_age_sex.head()

COUNTY             CTYNAME  POPESTIMATE  POPEST_MALE  POPEST_FEM  \
11       1       Albany County       305506       147818      157688   
23       3     Allegany County        46091        23418       22673   
35       5        Bronx County      1418207       669548      748659   
47       7       Broome County       190488        93845       96643   
59       9  Cattaraugus County        76117        37853       38264   

    UNDER5_TOT  AGE513_TOT  AGE1417_TOT  AGE1824_TOT  AGE18PLUS_TOT  \
11       15204       27656        12905        44050         249741   
23        2424        4589         2261         6687          36817   
35      100199      173858        74606       137701        1069544   
47        9886       18366         8553        27003         153683   
59        4160        8489         3987         6862          59481   

    AGE18PLUS_MALE  AGE18PLUS_FEM  AGE1544_TOT  AGE65PLUS_TOT  AGE2529_TOT  
11          119344         130397       130232          53272        21533  
23           18575          18242        17809           9055         2248  
35          491544         578000       600560         188766       119696  
47           74712          78971        74863          36980        11418  
59           29355          30126        26527          15022         4170

In [126]:
#clean county_name to consider join by county_name
county_pop_by_characteristics_age_sex['county_name'] = county_pop_by_characteristics_age_sex['CTYNAME'].str.rstrip('County').str.strip()

In [127]:
county_pop_by_characteristics_age_sex['county_name'].unique()

array(['Albany', 'Allegany', 'Bronx', 'Broome', 'Cattaraugus', 'Cayuga',
       'Chautauqua', 'Chemung', 'Chenango', 'Clinton', 'Columbia',
       'Cortland', 'Delaware', 'Dutchess', 'Erie', 'Essex', 'Franklin',
       'Fulton', 'Genesee', 'Greene', 'Hamilton', 'Herkimer', 'Jefferson',
       'Kings', 'Lewis', 'Livingston', 'Madison', 'Monroe', 'Montgomery',
       'Nassau', 'New York', 'Niagara', 'Oneida', 'Onondaga', 'Ontario',
       'Orange', 'Orleans', 'Oswego', 'Otsego', 'Putnam', 'Queens',
       'Rensselaer', 'Richmond', 'Rockland', 'St. Lawrence', 'Saratoga',
       'Schenectady', 'Schoharie', 'Schuyler', 'Seneca', 'Steuben',
       'Suffolk', 'Sullivan', 'Tioga', 'Tompkins', 'Ulster', 'Warren',
       'Washington', 'Wayne', 'Westchester', 'Wyoming', 'Yates'],
      dtype=object)

In [128]:
#Confirm county_name matches in main county df. If all true, yes! 
county_pop_by_characteristics_age_sex['match?'] = county_pop_by_characteristics_age_sex['county_name'].isin(county['county_name'])
county_pop_by_characteristics_age_sex['match?'].value_counts()

True    62
Name: match?, dtype: int64

In [129]:
del county_pop_by_characteristics_age_sex['match?']

great. That means that although FIPS is formatted slightly differently, name is a perfect match.

In [130]:
#create features to take out
county_pop_by_characteristics_age_sex.head(2)

COUNTY          CTYNAME  POPESTIMATE  POPEST_MALE  POPEST_FEM  UNDER5_TOT  \
11       1    Albany County       305506       147818      157688       15204   
23       3  Allegany County        46091        23418       22673        2424   

    AGE513_TOT  AGE1417_TOT  AGE1824_TOT  AGE18PLUS_TOT  AGE18PLUS_MALE  \
11       27656        12905        44050         249741          119344   
23        4589         2261         6687          36817           18575   

    AGE18PLUS_FEM  AGE1544_TOT  AGE65PLUS_TOT  AGE2529_TOT county_name  
11         130397       130232          53272        21533      Albany  
23          18242        17809           9055         2248    Allegany

In [131]:
#population
county_pop_by_characteristics_age_sex['population'] = county_pop_by_characteristics_age_sex['POPESTIMATE']

In [132]:
# % male and % female
county_pop_by_characteristics_age_sex['male_%'] = county_pop_by_characteristics_age_sex['POPEST_MALE']/county_pop_by_characteristics_age_sex['POPESTIMATE']
county_pop_by_characteristics_age_sex['female_%'] = county_pop_by_characteristics_age_sex['POPEST_FEM']/county_pop_by_characteristics_age_sex['POPESTIMATE']

In [133]:
county_pop_by_characteristics_age_sex.head(2)

COUNTY          CTYNAME  POPESTIMATE  POPEST_MALE  POPEST_FEM  UNDER5_TOT  \
11       1    Albany County       305506       147818      157688       15204   
23       3  Allegany County        46091        23418       22673        2424   

    AGE513_TOT  AGE1417_TOT  AGE1824_TOT  AGE18PLUS_TOT  AGE18PLUS_MALE  \
11       27656        12905        44050         249741          119344   
23        4589         2261         6687          36817           18575   

    AGE18PLUS_FEM  AGE1544_TOT  AGE65PLUS_TOT  AGE2529_TOT county_name  \
11         130397       130232          53272        21533      Albany   
23          18242        17809           9055         2248    Allegany   

    population    male_%  female_%  
11      305506  0.483846  0.516154  
23       46091  0.508082  0.491918

In [134]:
# age groups - 18-64, school-age-children, 65+
#elderly - vaccine priority
county_pop_by_characteristics_age_sex['65+age_%'] = county_pop_by_characteristics_age_sex['AGE65PLUS_TOT']/county_pop_by_characteristics_age_sex['POPESTIMATE']
#school-age children
county_pop_by_characteristics_age_sex['5-17age_%'] = county_pop_by_characteristics_age_sex['AGE65PLUS_TOT']/county_pop_by_characteristics_age_sex['POPESTIMATE']
#young adult - college age
county_pop_by_characteristics_age_sex['18-24age_%'] = county_pop_by_characteristics_age_sex['AGE1824_TOT']/county_pop_by_characteristics_age_sex['POPESTIMATE']

In [135]:
county_pop_by_characteristics_age_sex.head(2)

COUNTY          CTYNAME  POPESTIMATE  POPEST_MALE  POPEST_FEM  UNDER5_TOT  \
11       1    Albany County       305506       147818      157688       15204   
23       3  Allegany County        46091        23418       22673        2424   

    AGE513_TOT  AGE1417_TOT  AGE1824_TOT  AGE18PLUS_TOT  ...  AGE1544_TOT  \
11       27656        12905        44050         249741  ...       130232   
23        4589         2261         6687          36817  ...        17809   

    AGE65PLUS_TOT  AGE2529_TOT  county_name  population    male_%  female_%  \
11          53272        21533       Albany      305506  0.483846  0.516154   
23           9055         2248     Allegany       46091  0.508082  0.491918   

    65+age_%  5-17age_%  18-24age_%  
11  0.174373   0.174373    0.144187  
23  0.196459   0.196459    0.145083  

[2 rows x 22 columns]

In [136]:
county_pop_by_characteristics_age_sex.iloc[0]

COUNTY                        1
CTYNAME           Albany County
POPESTIMATE              305506
POPEST_MALE              147818
POPEST_FEM               157688
UNDER5_TOT                15204
AGE513_TOT                27656
AGE1417_TOT               12905
AGE1824_TOT               44050
AGE18PLUS_TOT            249741
AGE18PLUS_MALE           119344
AGE18PLUS_FEM            130397
AGE1544_TOT              130232
AGE65PLUS_TOT             53272
AGE2529_TOT               21533
county_name              Albany
population               305506
male_%                 0.483846
female_%               0.516154
65+age_%               0.174373
5-17age_%              0.174373
18-24age_%             0.144187
Name: 11, dtype: object

In [137]:
# limit to only columns requested. All normalized, except population
keep = ['county_name' , 'population', 'male_%','female_%','65+age_%','5-17age_%','18-24age_%']
county_pop_by_characteristics_age_sex = county_pop_by_characteristics_age_sex[keep]
del keep
county_pop_by_characteristics_age_sex.head()

county_name  population    male_%  female_%  65+age_%  5-17age_%  \
11       Albany      305506  0.483846  0.516154  0.174373   0.174373   
23     Allegany       46091  0.508082  0.491918  0.196459   0.196459   
35        Bronx     1418207  0.472109  0.527891  0.133102   0.133102   
47       Broome      190488  0.492656  0.507344  0.194133   0.194133   
59  Cattaraugus       76117  0.497300  0.502700  0.197354   0.197354   

    18-24age_%  
11    0.144187  
23    0.145083  
35    0.097095  
47    0.141757  
59    0.090151

In [138]:
#add to main df: county
county = county.merge(county_pop_by_characteristics_age_sex, left_on='county_name', right_on='county_name')
county.head()

FIPS  county_name  population    male_%  female_%  65+age_%  5-17age_%  \
0  36001       Albany      305506  0.483846  0.516154  0.174373   0.174373   
1  36003     Allegany       46091  0.508082  0.491918  0.196459   0.196459   
2  36005        Bronx     1418207  0.472109  0.527891  0.133102   0.133102   
3  36007       Broome      190488  0.492656  0.507344  0.194133   0.194133   
4  36009  Cattaraugus       76117  0.497300  0.502700  0.197354   0.197354   

   18-24age_%  
0    0.144187  
1    0.145083  
2    0.097095  
3    0.141757  
4    0.090151

In [139]:
len(county)

62

In [140]:
#county_pop_by_characteristics_age_sex_race_hispanic
county_pop_by_characteristics_age_sex_race_hispanic.head(3)

COUNTY          CTYNAME  TOT_POP  NH_MALE  NH_FEMALE  NHWA_MALE  \
209       1    Albany County   305506   138525     147879     105918   
437       3  Allegany County    46091    23001      22306      22004   
665       5     Bronx County  1418207   292853     325774      62733   

     NHWA_FEMALE  WA_MALE  WA_FEMALE  BA_MALE  ...  IA_MALE  IA_FEMALE  \
209       112727   112279     119259    20431  ...      456        474   
437        21452    22325      21723      403  ...       77         70   
665        65050   302291     331989   288327  ...    19830      21489   

     AA_MALE  AA_FEMALE  NA_MALE  NA_FEMALE  TOM_MALE  TOM_FEMALE  H_MALE  \
209    10189      10696      101        101      4362        4493    9293   
437      266        311        6         13       341         295     417   
665    31392      33294     2825       3150     24883       28508  376695   

     H_FEMALE  
209      9809  
437       367  
665    422885  

[3 rows x 21 columns]

In [141]:
# same as before. match on county name. 
county_pop_by_characteristics_age_sex_race_hispanic['county_name'] = county_pop_by_characteristics_age_sex_race_hispanic['CTYNAME'].str.rstrip('County').str.strip()

#Confirm county_name matches in main county df. If all true, yes! 
county_pop_by_characteristics_age_sex_race_hispanic['match?'] = county_pop_by_characteristics_age_sex_race_hispanic['county_name'].isin(county['county_name'])
county_pop_by_characteristics_age_sex_race_hispanic['match?'].value_counts()

True    62
Name: match?, dtype: int64

In [142]:
#confirm match on name.can delete helper column
del county_pop_by_characteristics_age_sex_race_hispanic['match?']

In [143]:
county_pop_by_characteristics_age_sex_race_hispanic.head(1)

COUNTY        CTYNAME  TOT_POP  NH_MALE  NH_FEMALE  NHWA_MALE  \
209       1  Albany County   305506   138525     147879     105918   

     NHWA_FEMALE  WA_MALE  WA_FEMALE  BA_MALE  ...  IA_FEMALE  AA_MALE  \
209       112727   112279     119259    20431  ...        474    10189   

     AA_FEMALE  NA_MALE  NA_FEMALE  TOM_MALE  TOM_FEMALE  H_MALE  H_FEMALE  \
209      10696      101        101      4362        4493    9293      9809   

     county_name  
209       Albany  

[1 rows x 22 columns]

We won't go too deep into nuances related to race, just bucket population by race with hispanics in their own bucket. Making buckets by age/race combination would be very inteteresting but is out of this project's scope as air quality is the big factor we are exploring but it would be a great follow up research.

We are excluding people who checked off white and other races but there is a two or more races bucket that will be used.

In [144]:
# white (male or female)
county_pop_by_characteristics_age_sex_race_hispanic['white_alone_%'] = (county_pop_by_characteristics_age_sex_race_hispanic['WA_MALE']+county_pop_by_characteristics_age_sex_race_hispanic['WA_FEMALE']) / county_pop_by_characteristics_age_sex_race_hispanic['TOT_POP']
#non hispanic white (male or female)
county_pop_by_characteristics_age_sex_race_hispanic['nh_white_alone_%'] = (county_pop_by_characteristics_age_sex_race_hispanic['NHWA_MALE']+county_pop_by_characteristics_age_sex_race_hispanic['NHWA_FEMALE']) / county_pop_by_characteristics_age_sex_race_hispanic['TOT_POP']

# Black or African American
county_pop_by_characteristics_age_sex_race_hispanic['black_african_amer_alone_%'] = (county_pop_by_characteristics_age_sex_race_hispanic['BA_MALE']+county_pop_by_characteristics_age_sex_race_hispanic['BA_FEMALE']) / county_pop_by_characteristics_age_sex_race_hispanic['TOT_POP']
# American Indian and Alaska Native
county_pop_by_characteristics_age_sex_race_hispanic['amer_indian_alask_alone_%'] = (county_pop_by_characteristics_age_sex_race_hispanic['IA_MALE']+county_pop_by_characteristics_age_sex_race_hispanic['IA_FEMALE']) / county_pop_by_characteristics_age_sex_race_hispanic['TOT_POP']
# Asian
county_pop_by_characteristics_age_sex_race_hispanic['asian_alone_%'] = (county_pop_by_characteristics_age_sex_race_hispanic['AA_MALE']+county_pop_by_characteristics_age_sex_race_hispanic['AA_FEMALE']) / county_pop_by_characteristics_age_sex_race_hispanic['TOT_POP']
#Two or More Races
county_pop_by_characteristics_age_sex_race_hispanic['2+_races_%'] = (county_pop_by_characteristics_age_sex_race_hispanic['TOM_MALE']+county_pop_by_characteristics_age_sex_race_hispanic['TOM_FEMALE']) / county_pop_by_characteristics_age_sex_race_hispanic['TOT_POP']
#Hispanic
county_pop_by_characteristics_age_sex_race_hispanic['hispanic_%'] = (county_pop_by_characteristics_age_sex_race_hispanic['H_MALE']+county_pop_by_characteristics_age_sex_race_hispanic['H_FEMALE']) / county_pop_by_characteristics_age_sex_race_hispanic['TOT_POP']

In [145]:
county_pop_by_characteristics_age_sex_race_hispanic.iloc[0]

COUNTY                                    1
CTYNAME                       Albany County
TOT_POP                              305506
NH_MALE                              138525
NH_FEMALE                            147879
NHWA_MALE                            105918
NHWA_FEMALE                          112727
WA_MALE                              112279
WA_FEMALE                            119259
BA_MALE                               20431
BA_FEMALE                             22665
IA_MALE                                 456
IA_FEMALE                               474
AA_MALE                               10189
AA_FEMALE                             10696
NA_MALE                                 101
NA_FEMALE                               101
TOM_MALE                               4362
TOM_FEMALE                             4493
H_MALE                                 9293
H_FEMALE                               9809
county_name                          Albany
white_alone_%                   

In [146]:
county_pop_by_characteristics_age_sex_race_hispanic.columns

Index(['COUNTY', 'CTYNAME', 'TOT_POP', 'NH_MALE', 'NH_FEMALE', 'NHWA_MALE',
       'NHWA_FEMALE', 'WA_MALE', 'WA_FEMALE', 'BA_MALE', 'BA_FEMALE',
       'IA_MALE', 'IA_FEMALE', 'AA_MALE', 'AA_FEMALE', 'NA_MALE', 'NA_FEMALE',
       'TOM_MALE', 'TOM_FEMALE', 'H_MALE', 'H_FEMALE', 'county_name',
       'white_alone_%', 'nh_white_alone_%', 'black_african_amer_alone_%',
       'amer_indian_alask_alone_%', 'asian_alone_%', '2+_races_%',
       'hispanic_%'],
      dtype='object')

Data for Albany County (not city) validated against data from census [HERE](https://www.census.gov/quickfacts/fact/table/albanycountynewyork/PST045219). Note, Hispanics are not being excluded from each bucket unless otherwise state (non-hispanic white alone)

In [147]:
# limit to only columns requested. All normalized, except population
keep = ['county_name','white_alone_%', 'nh_white_alone_%', 'black_african_amer_alone_%',
       'amer_indian_alask_alone_%', 'asian_alone_%', '2+_races_%','hispanic_%']
county_pop_by_characteristics_age_sex_race_hispanic = county_pop_by_characteristics_age_sex_race_hispanic[keep]
del keep
county_pop_by_characteristics_age_sex_race_hispanic.head()

county_name  white_alone_%  nh_white_alone_%  \
209        Albany       0.757884          0.715682   
437      Allegany       0.955675          0.942830   
665         Bronx       0.447241          0.090102   
893        Broome       0.858180          0.827002   
1121  Cattaraugus       0.918573          0.904266   

      black_african_amer_alone_%  amer_indian_alask_alone_%  asian_alone_%  \
209                     0.141064                   0.003044       0.068362   
437                     0.014406                   0.003189       0.012519   
665                     0.436154                   0.029135       0.045611   
893                     0.063605                   0.002725       0.044223   
1121                    0.014754                   0.036023       0.008474   

      2+_races_%  hispanic_%  
209     0.028985    0.062526  
437     0.013799    0.017010  
665     0.037647    0.563796  
893     0.030590    0.044496  
1121    0.021782    0.021480

In [148]:
#add to main df: county
county = county.merge(county_pop_by_characteristics_age_sex_race_hispanic, left_on='county_name', right_on='county_name')
county.head()

FIPS  county_name  population    male_%  female_%  65+age_%  5-17age_%  \
0  36001       Albany      305506  0.483846  0.516154  0.174373   0.174373   
1  36003     Allegany       46091  0.508082  0.491918  0.196459   0.196459   
2  36005        Bronx     1418207  0.472109  0.527891  0.133102   0.133102   
3  36007       Broome      190488  0.492656  0.507344  0.194133   0.194133   
4  36009  Cattaraugus       76117  0.497300  0.502700  0.197354   0.197354   

   18-24age_%  white_alone_%  nh_white_alone_%  black_african_amer_alone_%  \
0    0.144187       0.757884          0.715682                    0.141064   
1    0.145083       0.955675          0.942830                    0.014406   
2    0.097095       0.447241          0.090102                    0.436154   
3    0.141757       0.858180          0.827002                    0.063605   
4    0.090151       0.918573          0.904266                    0.014754   

   amer_indian_alask_alone_%  asian_alone_%  2+_races_%  hispanic_%  
0                   0.003044       0.068362    0.028985    0.062526  
1                   0.003189       0.012519    0.013799    0.017010  
2                   0.029135       0.045611    0.037647    0.563796  
3                   0.002725       0.044223    0.030590    0.044496  
4                   0.036023       0.008474    0.021782    0.021480

In [149]:
#County size
county_size.head()

County  Square Miles
0     Bronx         42.03
1     Kings         70.61
2  New York         22.96
3    Queens        109.24
4  Richmond         58.48

In [150]:
#Confirm county_name matches in main county df. If all true, yes! 
county_size['match?'] = county_size['County'].isin(county['county_name'])
county_size['match?'].value_counts()

True     61
False     1
Name: match?, dtype: int64

In [151]:
#1 does not match. Find and rename to match.
county_size.loc[county_size['match?']==False]

County  Square Miles  match?
44  St Lawrence        2685.6   False

In [152]:
county['county_name'].unique()

array(['Albany', 'Allegany', 'Bronx', 'Broome', 'Cattaraugus', 'Cayuga',
       'Chautauqua', 'Chemung', 'Chenango', 'Clinton', 'Columbia',
       'Cortland', 'Delaware', 'Dutchess', 'Erie', 'Essex', 'Franklin',
       'Fulton', 'Genesee', 'Greene', 'Hamilton', 'Herkimer', 'Jefferson',
       'Kings', 'Lewis', 'Livingston', 'Madison', 'Monroe', 'Montgomery',
       'Nassau', 'New York', 'Niagara', 'Oneida', 'Onondaga', 'Ontario',
       'Orange', 'Orleans', 'Oswego', 'Otsego', 'Putnam', 'Queens',
       'Rensselaer', 'Richmond', 'Rockland', 'St. Lawrence', 'Saratoga',
       'Schenectady', 'Schoharie', 'Schuyler', 'Seneca', 'Steuben',
       'Suffolk', 'Sullivan', 'Tioga', 'Tompkins', 'Ulster', 'Warren',
       'Washington', 'Wayne', 'Westchester', 'Wyoming', 'Yates'],
      dtype=object)

In [153]:
#Spelled St. Lawrence in county
county_size.replace('St Lawrence', 'St. Lawrence',inplace=True)

In [154]:
#confirm change made
county_size.iloc[44]

County          St. Lawrence
Square Miles          2685.6
match?                 False
Name: 44, dtype: object

In [155]:
#Confirm county_name matches in main county df. If all true, yes! 
county_size['match?'] = county_size['County'].isin(county['county_name'])
county_size['match?'].value_counts()

True    62
Name: match?, dtype: int64

In [156]:
#delete match field
del county_size['match?']

In [157]:
# add to main county df, note: adding a value (not normalized)
county = county.merge(county_size, left_on='county_name', right_on='County')
county.head()

FIPS  county_name  population    male_%  female_%  65+age_%  5-17age_%  \
0  36001       Albany      305506  0.483846  0.516154  0.174373   0.174373   
1  36003     Allegany       46091  0.508082  0.491918  0.196459   0.196459   
2  36005        Bronx     1418207  0.472109  0.527891  0.133102   0.133102   
3  36007       Broome      190488  0.492656  0.507344  0.194133   0.194133   
4  36009  Cattaraugus       76117  0.497300  0.502700  0.197354   0.197354   

   18-24age_%  white_alone_%  nh_white_alone_%  black_african_amer_alone_%  \
0    0.144187       0.757884          0.715682                    0.141064   
1    0.145083       0.955675          0.942830                    0.014406   
2    0.097095       0.447241          0.090102                    0.436154   
3    0.141757       0.858180          0.827002                    0.063605   
4    0.090151       0.918573          0.904266                    0.014754   

   amer_indian_alask_alone_%  asian_alone_%  2+_races_%  hispanic_%  \
0                   0.003044       0.068362    0.028985    0.062526   
1                   0.003189       0.012519    0.013799    0.017010   
2                   0.029135       0.045611    0.037647    0.563796   
3                   0.002725       0.044223    0.030590    0.044496   
4                   0.036023       0.008474    0.021782    0.021480   

        County  Square Miles  
0       Albany        523.45  
1     Allegany       1030.22  
2        Bronx         42.03  
3       Broome        706.82  
4  Cattaraugus       1309.85

In [158]:
#delete extra column
del county['County']
county.rename(columns={"Square Miles": "sq_miles"},inplace=True)
county.head()

FIPS  county_name  population    male_%  female_%  65+age_%  5-17age_%  \
0  36001       Albany      305506  0.483846  0.516154  0.174373   0.174373   
1  36003     Allegany       46091  0.508082  0.491918  0.196459   0.196459   
2  36005        Bronx     1418207  0.472109  0.527891  0.133102   0.133102   
3  36007       Broome      190488  0.492656  0.507344  0.194133   0.194133   
4  36009  Cattaraugus       76117  0.497300  0.502700  0.197354   0.197354   

   18-24age_%  white_alone_%  nh_white_alone_%  black_african_amer_alone_%  \
0    0.144187       0.757884          0.715682                    0.141064   
1    0.145083       0.955675          0.942830                    0.014406   
2    0.097095       0.447241          0.090102                    0.436154   
3    0.141757       0.858180          0.827002                    0.063605   
4    0.090151       0.918573          0.904266                    0.014754   

   amer_indian_alask_alone_%  asian_alone_%  2+_races_%  hispanic_%  sq_miles  
0                   0.003044       0.068362    0.028985    0.062526    523.45  
1                   0.003189       0.012519    0.013799    0.017010   1030.22  
2                   0.029135       0.045611    0.037647    0.563796     42.03  
3                   0.002725       0.044223    0.030590    0.044496    706.82  
4                   0.036023       0.008474    0.021782    0.021480   1309.85

In [159]:
poverty.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 62 entries, 1 to 62
Data columns (total 9 columns):
FIPS                62 non-null int64
Name                62 non-null object
RUC Code            62 non-null float64
Percent_Pop         62 non-null float64
Lower Bound         62 non-null float64
Upper Bound         62 non-null float64
Percent_Children    62 non-null float64
Lower Bound.1       62 non-null float64
Upper Bound.1       62 non-null float64
dtypes: float64(7), int64(1), object(1)
memory usage: 4.8+ KB


In [160]:
poverty.head(2)

FIPS      Name  RUC Code  Percent_Pop  Lower Bound  Upper Bound  \
1  36001    Albany       2.0         11.7         10.2         13.2   
2  36003  Allegany       7.0         17.9         15.0         20.8   

   Percent_Children  Lower Bound.1  Upper Bound.1  
1              16.0           13.1           18.9  
2              26.8           21.2           32.4

I will only be using the Percept_Pop population which represents the percent of total population in poverty.

In [161]:
#change % to decimal to match others
poverty['pop_in_poverty_%'] = poverty['Percent_Pop']/100

In [162]:
poverty.head()

FIPS         Name  RUC Code  Percent_Pop  Lower Bound  Upper Bound  \
1  36001       Albany       2.0         11.7         10.2         13.2   
2  36003     Allegany       7.0         17.9         15.0         20.8   
3  36005        Bronx       1.0         26.2         24.9         27.5   
4  36007       Broome       2.0         17.8         15.8         19.8   
5  36009  Cattaraugus       4.0         14.7         12.5         16.9   

   Percent_Children  Lower Bound.1  Upper Bound.1  pop_in_poverty_%  
1              16.0           13.1           18.9             0.117  
2              26.8           21.2           32.4             0.179  
3              36.5           33.8           39.2             0.262  
4              24.9           20.7           29.1             0.178  
5              21.5           16.5           26.5             0.147

In [163]:
poverty = poverty[['FIPS', 'pop_in_poverty_%']]
poverty.head()

FIPS  pop_in_poverty_%
1  36001             0.117
2  36003             0.179
3  36005             0.262
4  36007             0.178
5  36009             0.147

In [164]:
# add to main county df
county = county.merge(poverty, left_on='FIPS', right_on='FIPS')
county.head()

FIPS  county_name  population    male_%  female_%  65+age_%  5-17age_%  \
0  36001       Albany      305506  0.483846  0.516154  0.174373   0.174373   
1  36003     Allegany       46091  0.508082  0.491918  0.196459   0.196459   
2  36005        Bronx     1418207  0.472109  0.527891  0.133102   0.133102   
3  36007       Broome      190488  0.492656  0.507344  0.194133   0.194133   
4  36009  Cattaraugus       76117  0.497300  0.502700  0.197354   0.197354   

   18-24age_%  white_alone_%  nh_white_alone_%  black_african_amer_alone_%  \
0    0.144187       0.757884          0.715682                    0.141064   
1    0.145083       0.955675          0.942830                    0.014406   
2    0.097095       0.447241          0.090102                    0.436154   
3    0.141757       0.858180          0.827002                    0.063605   
4    0.090151       0.918573          0.904266                    0.014754   

   amer_indian_alask_alone_%  asian_alone_%  2+_races_%  hispanic_%  sq_miles  \
0                   0.003044       0.068362    0.028985    0.062526    523.45   
1                   0.003189       0.012519    0.013799    0.017010   1030.22   
2                   0.029135       0.045611    0.037647    0.563796     42.03   
3                   0.002725       0.044223    0.030590    0.044496    706.82   
4                   0.036023       0.008474    0.021782    0.021480   1309.85   

   pop_in_poverty_%  
0             0.117  
1             0.179  
2             0.262  
3             0.178  
4             0.147

In [165]:
unemployment_income.head(2)

FIPS                 Name  2019 Unemployment Rate  \
1  36001    Albany County, NY                     3.6   
2  36003  Allegany County, NY                     5.5   

  Median Household Income (2019)  
1                        $69,408  
2                        $49,411

In [166]:
unemployment_income.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 62 entries, 1 to 62
Data columns (total 4 columns):
FIPS                              62 non-null int64
Name                              62 non-null object
2019 Unemployment Rate            62 non-null float64
Median Household Income (2019)    62 non-null object
dtypes: float64(1), int64(1), object(2)
memory usage: 2.4+ KB


In [167]:
#prep to change income to number
unemployment_income['Median Household Income (2019)'] = unemployment_income['Median Household Income (2019)'].str.replace('$','').str.replace(',','')

In [168]:
unemployment_income.head(2)

FIPS                 Name  2019 Unemployment Rate  \
1  36001    Albany County, NY                     3.6   
2  36003  Allegany County, NY                     5.5   

  Median Household Income (2019)  
1                          69408  
2                          49411

In [169]:
unemployment_income['Median Household Income (2019)'] = unemployment_income['Median Household Income (2019)'].astype(int)

In [170]:
unemployment_income.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 62 entries, 1 to 62
Data columns (total 4 columns):
FIPS                              62 non-null int64
Name                              62 non-null object
2019 Unemployment Rate            62 non-null float64
Median Household Income (2019)    62 non-null int32
dtypes: float64(1), int32(1), int64(1), object(1)
memory usage: 2.2+ KB


In [171]:
#change to decimal like other values
unemployment_income['2019 Unemployment Rate'] = unemployment_income['2019 Unemployment Rate']/100

Note, using unemployment rate as of 2019 as it won't be affected by COVID-related changes in unemployment

In [172]:
#rename columns
unemployment_income.rename(columns={"2019 Unemployment Rate": "unemployment_rate", "Median Household Income (2019)": "median_household_income"},inplace=True)
unemployment_income.head(2)

FIPS                 Name  unemployment_rate  median_household_income
1  36001    Albany County, NY              0.036                    69408
2  36003  Allegany County, NY              0.055                    49411

In [173]:
# drop extra columns
unemployment_income = unemployment_income[['FIPS', 'unemployment_rate', 'median_household_income']]

In [174]:
# add to main county df
county = county.merge(unemployment_income, left_on='FIPS', right_on='FIPS')
county.head(2)

FIPS county_name  population    male_%  female_%  65+age_%  5-17age_%  \
0  36001      Albany      305506  0.483846  0.516154  0.174373   0.174373   
1  36003    Allegany       46091  0.508082  0.491918  0.196459   0.196459   

   18-24age_%  white_alone_%  nh_white_alone_%  black_african_amer_alone_%  \
0    0.144187       0.757884          0.715682                    0.141064   
1    0.145083       0.955675          0.942830                    0.014406   

   amer_indian_alask_alone_%  asian_alone_%  2+_races_%  hispanic_%  sq_miles  \
0                   0.003044       0.068362    0.028985    0.062526    523.45   
1                   0.003189       0.012519    0.013799    0.017010   1030.22   

   pop_in_poverty_%  unemployment_rate  median_household_income  
0             0.117              0.036                    69408  
1             0.179              0.055                    49411

In [175]:
hospitals.head(2)

X             Y  OBJECTID       ID  \
262 -8.230494e+06  5.115231e+06       264  2912601   
263 -8.775443e+06  5.300575e+06       265  3214215   

                               NAME        ADDRESS          CITY STATE    ZIP  \
262  VASSAR BROTHERS MEDICAL CENTER    45 READE PL  POUGHKEEPSIE    NY  12601   
263      ERIE COUNTY MEDICAL CENTER  462 GRIDER ST       BUFFALO    NY  14215   

              ZIP4  ...             VAL_DATE  \
262  NOT AVAILABLE  ...  2014/02/10 00:00:00   
263  NOT AVAILABLE  ...  2014/03/12 00:00:00   

                                               WEBSITE  STATE_ID  \
262  http://www.healthquest.org/poughkeepsie/vassar...  1302001H   
263                                http://www.ecmc.edu  1401005H   

          ALT_NAME ST_FIPS                            OWNER TTL_STAFF  BEDS  \
262  NOT AVAILABLE      36                       NON-PROFIT      -999   365   
263  NOT AVAILABLE      36  GOVERNMENT - DISTRICT/AUTHORITY      -999   550   

       TRAUMA  HELIPAD  
262  LEVEL II        Y  
263   LEVEL I        Y  

[2 rows x 34 columns]

In [176]:
hospitals.iloc[0]

X                                                  -8.23049e+06
Y                                                   5.11523e+06
OBJECTID                                                    264
ID                                                      2912601
NAME                             VASSAR BROTHERS MEDICAL CENTER
ADDRESS                                             45 READE PL
CITY                                               POUGHKEEPSIE
STATE                                                        NY
ZIP                                                       12601
ZIP4                                              NOT AVAILABLE
TELEPHONE                                        (845) 454-8500
TYPE                                         GENERAL ACUTE CARE
STATUS                                                     OPEN
POPULATION                                                  365
COUNTY                                                 DUTCHESS
COUNTYFIPS                              

change to hospital count per county

In [177]:
hospitals = hospitals.groupby(['COUNTYFIPS'])['BEDS'].sum()
hospitals = hospitals.to_frame().rename(columns={'BEDS':'hospital_beds'})
hospitals = hospitals.reset_index()
hospitals['hospital_beds'].value_counts()

 25      3
 67      2
 126     1
 1184    1
-600     1
 344     1
 300     1
 169     1
 40      1
 39      1
-461     1
 164     1
 162     1
 926     1
 31      1
 2236    1
 158     1
 1932    1
 410     1
 1558    1
 1169    1
 399     1
 1292    1
 4995    1
 130     1
 186     1
 3377    1
 423     1
 99      1
 62      1
 4600    1
 240     1
 623     1
-868     1
-345     1
 471     1
 853     1
 212     1
 7503    1
 76      1
 74      1
 120     1
 325     1
-959     1
 192     1
 319     1
 3646    1
 445     1
 259     1
 1213    1
 58      1
-826     1
 1207    1
 4736    1
Name: hospital_beds, dtype: int64

In [178]:
hospitals.head()

COUNTYFIPS  hospital_beds
0      36001           1558
1      36003             76
2      36005           1292
3      36007            853
4      36009            186

In [179]:
hospitals.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57 entries, 0 to 56
Data columns (total 2 columns):
COUNTYFIPS       57 non-null object
hospital_beds    57 non-null int64
dtypes: int64(1), object(1)
memory usage: 1.0+ KB


In [180]:
hospitals['COUNTYFIPS'] = hospitals['COUNTYFIPS'].astype(int)
hospitals.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57 entries, 0 to 56
Data columns (total 2 columns):
COUNTYFIPS       57 non-null int32
hospital_beds    57 non-null int64
dtypes: int32(1), int64(1)
memory usage: 812.0 bytes


In [181]:
# add to main county df
county = county.merge(hospitals, how='left', left_on='FIPS', right_on='COUNTYFIPS')
county.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 62 entries, 0 to 61
Data columns (total 21 columns):
FIPS                          62 non-null int64
county_name                   62 non-null object
population                    62 non-null int64
male_%                        62 non-null float64
female_%                      62 non-null float64
65+age_%                      62 non-null float64
5-17age_%                     62 non-null float64
18-24age_%                    62 non-null float64
white_alone_%                 62 non-null float64
nh_white_alone_%              62 non-null float64
black_african_amer_alone_%    62 non-null float64
amer_indian_alask_alone_%     62 non-null float64
asian_alone_%                 62 non-null float64
2+_races_%                    62 non-null float64
hispanic_%                    62 non-null float64
sq_miles                      62 non-null float64
pop_in_poverty_%              62 non-null float64
unemployment_rate             62 non-null float64
me

In [182]:
#delete extra column
del county['COUNTYFIPS']

In [183]:
county.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 62 entries, 0 to 61
Data columns (total 20 columns):
FIPS                          62 non-null int64
county_name                   62 non-null object
population                    62 non-null int64
male_%                        62 non-null float64
female_%                      62 non-null float64
65+age_%                      62 non-null float64
5-17age_%                     62 non-null float64
18-24age_%                    62 non-null float64
white_alone_%                 62 non-null float64
nh_white_alone_%              62 non-null float64
black_african_amer_alone_%    62 non-null float64
amer_indian_alask_alone_%     62 non-null float64
asian_alone_%                 62 non-null float64
2+_races_%                    62 non-null float64
hispanic_%                    62 non-null float64
sq_miles                      62 non-null float64
pop_in_poverty_%              62 non-null float64
unemployment_rate             62 non-null float64
me

In [184]:
#only null in hospital count. Should be 0
county.fillna(0,inplace=True)

In [185]:
county.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 62 entries, 0 to 61
Data columns (total 20 columns):
FIPS                          62 non-null int64
county_name                   62 non-null object
population                    62 non-null int64
male_%                        62 non-null float64
female_%                      62 non-null float64
65+age_%                      62 non-null float64
5-17age_%                     62 non-null float64
18-24age_%                    62 non-null float64
white_alone_%                 62 non-null float64
nh_white_alone_%              62 non-null float64
black_african_amer_alone_%    62 non-null float64
amer_indian_alask_alone_%     62 non-null float64
asian_alone_%                 62 non-null float64
2+_races_%                    62 non-null float64
hispanic_%                    62 non-null float64
sq_miles                      62 non-null float64
pop_in_poverty_%              62 non-null float64
unemployment_rate             62 non-null float64
me

Next: normalize population by using **population density** instead which as per the [U.S. Census website](https://www.census.gov/newsroom/blogs/random-samplings/2015/03/understanding-population-density.html), it "is typically expressed as the number of people per square mile of land area."

In [186]:
county['pop_density'] = county['population'] / county['sq_miles']

In [187]:
county.iloc[0]

FIPS                               36001
county_name                       Albany
population                        305506
male_%                          0.483846
female_%                        0.516154
65+age_%                        0.174373
5-17age_%                       0.174373
18-24age_%                      0.144187
white_alone_%                   0.757884
nh_white_alone_%                0.715682
black_african_amer_alone_%      0.141064
amer_indian_alask_alone_%     0.00304413
asian_alone_%                   0.068362
2+_races_%                     0.0289847
hispanic_%                     0.0625258
sq_miles                          523.45
pop_in_poverty_%                   0.117
unemployment_rate                  0.036
median_household_income            69408
hospital_beds                       1558
pop_density                      583.639
Name: 0, dtype: object

Normalize hospital count: We will use **hospital beds per 1000 population** as used by the [World Health Organization (WHO)](https://www.who.int/data/gho/indicator-metadata-registry/imr-details/3119) and other government organizations



In [188]:
county['hospital_beds_per_1K'] = county['hospital_beds'] / (county['population']/1000)

In [189]:
county.head()

FIPS  county_name  population    male_%  female_%  65+age_%  5-17age_%  \
0  36001       Albany      305506  0.483846  0.516154  0.174373   0.174373   
1  36003     Allegany       46091  0.508082  0.491918  0.196459   0.196459   
2  36005        Bronx     1418207  0.472109  0.527891  0.133102   0.133102   
3  36007       Broome      190488  0.492656  0.507344  0.194133   0.194133   
4  36009  Cattaraugus       76117  0.497300  0.502700  0.197354   0.197354   

   18-24age_%  white_alone_%  nh_white_alone_%  ...  asian_alone_%  \
0    0.144187       0.757884          0.715682  ...       0.068362   
1    0.145083       0.955675          0.942830  ...       0.012519   
2    0.097095       0.447241          0.090102  ...       0.045611   
3    0.141757       0.858180          0.827002  ...       0.044223   
4    0.090151       0.918573          0.904266  ...       0.008474   

   2+_races_%  hispanic_%  sq_miles  pop_in_poverty_%  unemployment_rate  \
0    0.028985    0.062526    523.45             0.117              0.036   
1    0.013799    0.017010   1030.22             0.179              0.055   
2    0.037647    0.563796     42.03             0.262              0.054   
3    0.030590    0.044496    706.82             0.178              0.047   
4    0.021782    0.021480   1309.85             0.147              0.051   

   median_household_income  hospital_beds   pop_density  hospital_beds_per_1K  
0                    69408         1558.0    583.639316              5.099736  
1                    49411           76.0     44.738988              1.648912  
2                    41470         1292.0  33742.731382              0.911009  
3                    52179          853.0    269.500014              4.477972  
4                    50783          186.0     58.111234              2.443607  

[5 rows x 22 columns]

In [190]:
# county dataframe
county.iloc[0]

FIPS                               36001
county_name                       Albany
population                        305506
male_%                          0.483846
female_%                        0.516154
65+age_%                        0.174373
5-17age_%                       0.174373
18-24age_%                      0.144187
white_alone_%                   0.757884
nh_white_alone_%                0.715682
black_african_amer_alone_%      0.141064
amer_indian_alask_alone_%     0.00304413
asian_alone_%                   0.068362
2+_races_%                     0.0289847
hispanic_%                     0.0625258
sq_miles                          523.45
pop_in_poverty_%                   0.117
unemployment_rate                  0.036
median_household_income            69408
hospital_beds                       1558
pop_density                      583.639
hospital_beds_per_1K             5.09974
Name: 0, dtype: object

All county parameters aggregated to one df. Now, need to consider connection with other data. Note population, sq_miles, and hospital_beds are in whole values.

**Which parameter to choose?**

In [191]:
aqi_breakpoints['Parameter'].unique()

array(['Acceptable PM2.5 AQI & Speciation Mass', 'Carbon monoxide',
       'Nitrogen dioxide (NO2)', 'Ozone', 'PM10 Total 0-10um STP',
       'PM2.5 - Local Conditions', 'Sulfur dioxide'], dtype=object)

In [192]:
aqi_breakpoints['Parameter Code'].unique()

array([88502, 42101, 42602, 44201, 81102, 88101, 42401], dtype=int64)

In [193]:
air_2010_2020['AQS_PARAMETER_DESC'].unique()

array(['PM2.5 - Local Conditions',
       'Acceptable PM2.5 AQI & Speciation Mass'], dtype=object)

In [194]:
air_2010_2020['AQS_PARAMETER_DESC'].unique()

array(['PM2.5 - Local Conditions',
       'Acceptable PM2.5 AQI & Speciation Mass'], dtype=object)

Based on what EPA's [uses for its annual summary statistics](https://www.epa.gov/outdoor-air-quality-data/air-data-frequent-questions#8), let's attempt to use only one parameter: PM2.5 - Local Conditions. 

**Add air quality metrics to county dataframe**

In [195]:
#should be left with 1 scale from "good" to "hazardous"
aqi_breakpoints = aqi_breakpoints.loc[(aqi_breakpoints['Parameter Code'] == 88101) & (aqi_breakpoints['Duration Description'] == '24-HR BLK AVG')]
aqi_breakpoints

Parameter  Parameter Code Duration Code  \
69  PM2.5 - Local Conditions           88101             X   
70  PM2.5 - Local Conditions           88101             X   
71  PM2.5 - Local Conditions           88101             X   
72  PM2.5 - Local Conditions           88101             X   
73  PM2.5 - Local Conditions           88101             X   
74  PM2.5 - Local Conditions           88101             X   
75  PM2.5 - Local Conditions           88101             X   
76  PM2.5 - Local Conditions           88101             X   

   Duration Description             AQI Category  Low AQI  High AQI  \
69        24-HR BLK AVG                     GOOD        0        50   
70        24-HR BLK AVG                 MODERATE       51       100   
71        24-HR BLK AVG  UNHEALTHY FOR SENSITIVE      101       150   
72        24-HR BLK AVG                UNHEALTHY      151       200   
73        24-HR BLK AVG           VERY UNHEALTHY      201       300   
74        24-HR BLK AVG                HAZARDOUS      301       400   
75        24-HR BLK AVG                HAZARDOUS      401       500   
76        24-HR BLK AVG                HAZARDOUS      501       999   

    Low Breakpoint  High Breakpoint  
69             0.0             12.0  
70            12.1             35.4  
71            35.5             55.4  
72            55.5            150.4  
73           150.5            250.4  
74           250.5            350.4  
75           350.5            500.4  
76           500.5          99999.9

Above 100 AQI is considered unhealthy for sensitive people

In [196]:
air_2010_2020 = air_2010_2020.loc[air_2010_2020['AQS_PARAMETER_CODE'] == 88101]

In [197]:
# confirm only 1 left
air_2010_2020['AQS_PARAMETER_DESC'].unique()

array(['PM2.5 - Local Conditions'], dtype=object)

In [198]:
air_2010_2020.head()

Date    Site ID  Daily Mean PM2.5 Concentration     UNITS  \
0 2010-01-01  360010005                            22.5  ug/m3 LC   
1 2010-01-02  360010005                             3.2  ug/m3 LC   
2 2010-01-03  360010005                             3.8  ug/m3 LC   
3 2010-01-04  360010005                             2.3  ug/m3 LC   
4 2010-01-08  360010005                             3.4  ug/m3 LC   

   DAILY_AQI_VALUE                  Site Name  AQS_PARAMETER_CODE  \
0               73  ALBANY COUNTY HEALTH DEPT               88101   
1               13  ALBANY COUNTY HEALTH DEPT               88101   
2               16  ALBANY COUNTY HEALTH DEPT               88101   
3               10  ALBANY COUNTY HEALTH DEPT               88101   
4               14  ALBANY COUNTY HEALTH DEPT               88101   

         AQS_PARAMETER_DESC  COUNTY_CODE  COUNTY  SITE_LATITUDE  \
0  PM2.5 - Local Conditions            1  Albany       42.64225   
1  PM2.5 - Local Conditions            1  Albany       42.64225   
2  PM2.5 - Local Conditions            1  Albany       42.64225   
3  PM2.5 - Local Conditions            1  Albany       42.64225   
4  PM2.5 - Local Conditions            1  Albany       42.64225   

   SITE_LONGITUDE  year  
0       -73.75464  2010  
1       -73.75464  2010  
2       -73.75464  2010  
3       -73.75464  2010  
4       -73.75464  2010

For air quality, I want to check the air quality over 3 periods of time - 2020, the 5 years before, and the 5 year before that. It will be important to see which counties have improved on air quality.  

In [199]:
#creating metrics for 2010-2014
air_2010_2014 = air_2010_2020.loc[air_2010_2020['year'].isin([2010,2011,2012,2013,2014])].copy()

In [200]:
#Average AQI - 2010_2014
air_2010_2014_aqi = air_2010_2014.groupby(['COUNTY'])['DAILY_AQI_VALUE'].mean().to_frame().reset_index().rename(columns={'DAILY_AQI_VALUE':'2010-2014_avg_daily_aqi'})
air_2010_2014_aqi

COUNTY  2010-2014_avg_daily_aqi
0        Albany                30.521718
1         Bronx                37.220349
2    Chautauqua                30.103825
3          Erie                35.966692
4         Essex                17.216606
5         Kings                37.566071
6        Monroe                30.623803
7        Nassau                34.874439
8      New York                39.585442
9       Niagara                32.951140
10     Onondaga                27.565912
11       Orange                30.996516
12       Queens                33.533567
13     Richmond                34.985733
14      Steuben                26.264574
15      Suffolk                32.135182
16  Westchester                35.472803

Purposely picked average and not median as I do want to have effects of outliers. One day with unhealthy air is a problem.

Only have data on 16 counties.

In [201]:
#how many days were unhealthy or hazardous
air_2010_2014['unhealthy_aqi?'] = np.where(air_2010_2014['DAILY_AQI_VALUE']>100, 1,0)

In [202]:
air_2010_2014['unhealthy_aqi?'].value_counts()

0    15877
1       18
Name: unhealthy_aqi?, dtype: int64

In [203]:
#observation rate of Unhealthy > Hazardous AQI  - 2010_2014
air_2010_2014_unhealthy = air_2010_2014.groupby('COUNTY').agg({'unhealthy_aqi?': 'sum', 'Date': 'count'}).reset_index().rename(columns={'unhealthy_aqi?':'unhealthy_aqi_obs', 'Date':'obs_count'})
air_2010_2014_unhealthy['2010-2014_unhealthy_aqi_observed_rate_%'] = air_2010_2014_unhealthy['unhealthy_aqi_obs'] / air_2010_2014_unhealthy['obs_count']
air_2010_2014_unhealthy = air_2010_2014_unhealthy[['COUNTY', '2010-2014_unhealthy_aqi_observed_rate_%']]
air_2010_2014_unhealthy

COUNTY  2010-2014_unhealthy_aqi_observed_rate_%
0        Albany                                 0.000477
1         Bronx                                 0.002811
2    Chautauqua                                 0.000000
3          Erie                                 0.001514
4         Essex                                 0.000000
5         Kings                                 0.001786
6        Monroe                                 0.001368
7        Nassau                                 0.000000
8      New York                                 0.001332
9       Niagara                                 0.000000
10     Onondaga                                 0.000000
11       Orange                                 0.001742
12       Queens                                 0.001002
13     Richmond                                 0.001297
14      Steuben                                 0.000000
15      Suffolk                                 0.000000
16  Westchester                                 0.004184

As unhealhy not very common, let's report on moderate > hazarous AQI. Moderate AQI is considered 51-100.  

In [204]:
#how many observations were of moderate AQI
air_2010_2014['moderate+_aqi?'] = np.where(air_2010_2014['DAILY_AQI_VALUE']>50, 1,0)
air_2010_2014['moderate+_aqi?'].value_counts()

0    12738
1     3157
Name: moderate+_aqi?, dtype: int64

In [205]:
air_2010_2014.head(1)

Date    Site ID  Daily Mean PM2.5 Concentration     UNITS  \
0 2010-01-01  360010005                            22.5  ug/m3 LC   

   DAILY_AQI_VALUE                  Site Name  AQS_PARAMETER_CODE  \
0               73  ALBANY COUNTY HEALTH DEPT               88101   

         AQS_PARAMETER_DESC  COUNTY_CODE  COUNTY  SITE_LATITUDE  \
0  PM2.5 - Local Conditions            1  Albany       42.64225   

   SITE_LONGITUDE  year  unhealthy_aqi?  moderate+_aqi?  
0       -73.75464  2010               0               1

In [206]:
#observation rate of Moderate> Hazardous AQI - 2010_2014
air_2010_2014_moderate_plus = air_2010_2014.groupby('COUNTY').agg({'moderate+_aqi?': 'sum', 'Date': 'count'}).reset_index().rename(columns={'moderate+_aqi?':'moderate_aqi_obs', 'Date':'obs_count'})
air_2010_2014_moderate_plus['2010-2014_moderate_plus_aqi_observed_rate_%'] = air_2010_2014_moderate_plus['moderate_aqi_obs'] / air_2010_2014_moderate_plus['obs_count']
air_2010_2014_moderate_plus = air_2010_2014_moderate_plus[['COUNTY', '2010-2014_moderate_plus_aqi_observed_rate_%']]
air_2010_2014_moderate_plus

COUNTY  2010-2014_moderate_plus_aqi_observed_rate_%
0        Albany                                     0.161814
1         Bronx                                     0.253513
2    Chautauqua                                     0.156648
3          Erie                                     0.235428
4         Essex                                     0.032491
5         Kings                                     0.258929
6        Monroe                                     0.155951
7        Nassau                                     0.233184
8      New York                                     0.280959
9       Niagara                                     0.182410
10     Onondaga                                     0.111851
11       Orange                                     0.160279
12       Queens                                     0.186373
13     Richmond                                     0.210117
14      Steuben                                     0.102018
15      Suffolk                                     0.173310
16  Westchester                                     0.251046

For the period 2010 - 2014, I have calculated the average daily AQI value and the observation rate of unhealthy-hazardous AQIs and  moderate - hazardous AQI. Doing the same for other 2 periods.

In [207]:
#creating metrics for 2015-2019
air_2015_2019 = air_2010_2020.loc[air_2010_2020['year'].isin([2015,2016,2017,2018,2019])].copy()

In [208]:
#Average AQI - 2015-2019
air_2015_2019_aqi = air_2015_2019.groupby(['COUNTY'])['DAILY_AQI_VALUE'].mean().to_frame().reset_index().rename(columns={'DAILY_AQI_VALUE':'2015-2019_avg_daily_aqi'})
air_2015_2019_aqi

COUNTY  2015-2019_avg_daily_aqi
0       Albany                27.791179
1        Bronx                30.152561
2   Chautauqua                26.420593
3         Erie                29.183249
4        Essex                15.106762
5        Kings                32.287648
6       Monroe                26.478982
7     New York                34.666356
8     Onondaga                22.864166
9       Orange                26.250859
10      Queens                27.791089
11    Richmond                30.955437
12     Steuben                20.969021
13     Suffolk                27.657040

In [209]:
#how many days were unhealthy or hazardous
air_2015_2019['unhealthy_aqi?'] = np.where(air_2015_2019['DAILY_AQI_VALUE']>100, 1,0)
air_2015_2019['unhealthy_aqi?'].value_counts()

0    22916
1        1
Name: unhealthy_aqi?, dtype: int64

Just one! Air quality seems to be getting better

In [210]:
#Observation Rate Unhealthy > Hazardous AQI levels- 2015_2019
air_2015_2019_unhealthy = air_2015_2019.groupby('COUNTY').agg({'unhealthy_aqi?': 'sum', 'Date': 'count'}).reset_index().rename(columns={'unhealthy_aqi?':'unhealthy_aqi_obs', 'Date':'obs_count'})
air_2015_2019_unhealthy['2015-2019_unhealthy_aqi_observed_rate_%'] = air_2015_2019_unhealthy['unhealthy_aqi_obs'] / air_2015_2019_unhealthy['obs_count']
air_2015_2019_unhealthy = air_2015_2019_unhealthy[['COUNTY','2015-2019_unhealthy_aqi_observed_rate_%']]
air_2015_2019_unhealthy

COUNTY  2015-2019_unhealthy_aqi_observed_rate_%
0       Albany                                 0.000000
1        Bronx                                 0.000000
2   Chautauqua                                 0.000000
3         Erie                                 0.000000
4        Essex                                 0.000000
5        Kings                                 0.000000
6       Monroe                                 0.000000
7     New York                                 0.000467
8     Onondaga                                 0.000000
9       Orange                                 0.000000
10      Queens                                 0.000000
11    Richmond                                 0.000000
12     Steuben                                 0.000000
13     Suffolk                                 0.000000

In [211]:
#how many observations were of moderate AQI
air_2015_2019['moderate+_aqi?'] = np.where(air_2015_2019['DAILY_AQI_VALUE']>50, 1,0)
air_2015_2019['moderate+_aqi?'].value_counts()

0    20495
1     2422
Name: moderate+_aqi?, dtype: int64

In [212]:
#observation rate of Moderate> Hazardous AQI - 2015-19
air_2015_2019_moderate_plus = air_2015_2019.groupby('COUNTY').agg({'moderate+_aqi?': 'sum', 'Date': 'count'}).reset_index().rename(columns={'moderate+_aqi?':'moderate_aqi_obs', 'Date':'obs_count'})
air_2015_2019_moderate_plus['2015-2019_moderate_plus_aqi_observed_rate_%'] = air_2015_2019_moderate_plus['moderate_aqi_obs'] / air_2015_2019_moderate_plus['obs_count']
air_2015_2019_moderate_plus = air_2015_2019_moderate_plus[['COUNTY','2015-2019_moderate_plus_aqi_observed_rate_%']]
air_2015_2019_moderate_plus

COUNTY  2015-2019_moderate_plus_aqi_observed_rate_%
0       Albany                                     0.101874
1        Bronx                                     0.150334
2   Chautauqua                                     0.085515
3         Erie                                     0.117128
4        Essex                                     0.014235
5        Kings                                     0.160745
6       Monroe                                     0.087929
7     New York                                     0.185721
8     Onondaga                                     0.052609
9       Orange                                     0.067010
10      Queens                                     0.115186
11    Richmond                                     0.151515
12     Steuben                                     0.033713
13     Suffolk                                     0.093863

In [213]:
#creating metrics for 2020
air_2020 = air_2010_2020.loc[air_2010_2020['year'].isin([2020])].copy()

In [214]:
#Average AQI - 2020
air_2020_aqi = air_2020.groupby(['COUNTY'])['DAILY_AQI_VALUE'].mean().to_frame().reset_index().rename(columns={'DAILY_AQI_VALUE':'2020_avg_daily_aqi'})
air_2020_aqi

COUNTY  2020_avg_daily_aqi
0       Albany           30.384752
1        Bronx           31.761693
2   Chautauqua           22.946809
3         Erie           26.497238
4        Essex           13.687500
5        Kings           29.490196
6       Monroe           26.740550
7     New York           30.696970
8     Onondaga           24.995316
9       Orange           25.430556
10      Queens           25.337778
11    Richmond           32.000000
12     Steuben           22.152620
13     Suffolk           26.166667

In [215]:
#how many days were unhealthy or hazardous
air_2020['unhealthy_aqi?'] = np.where(air_2020['DAILY_AQI_VALUE']>100, 1,0)
air_2020['unhealthy_aqi?'].value_counts()

0    4002
1       6
Name: unhealthy_aqi?, dtype: int64

In [216]:
#Observation Rate Unhealthy > Hazardous AQI levels- 2015_2019
air_2020_unhealthy = air_2020.groupby('COUNTY').agg({'unhealthy_aqi?': 'sum', 'Date': 'count'}).reset_index().rename(columns={'unhealthy_aqi?':'unhealthy_aqi_obs', 'Date':'obs_count'})
air_2020_unhealthy['2020_unhealthy_aqi_observed_rate_%'] = air_2020_unhealthy['unhealthy_aqi_obs'] / air_2020_unhealthy['obs_count']
air_2020_unhealthy = air_2020_unhealthy[['COUNTY','2020_unhealthy_aqi_observed_rate_%']]
air_2020_unhealthy

COUNTY  2020_unhealthy_aqi_observed_rate_%
0       Albany                            0.007092
1        Bronx                            0.000000
2   Chautauqua                            0.000000
3         Erie                            0.005525
4        Essex                            0.000000
5        Kings                            0.000000
6       Monroe                            0.000000
7     New York                            0.000000
8     Onondaga                            0.000000
9       Orange                            0.000000
10      Queens                            0.000000
11    Richmond                            0.000000
12     Steuben                            0.000000
13     Suffolk                            0.000000

In [217]:
#how many observations were of moderate AQI
air_2020['moderate+_aqi?'] = np.where(air_2020['DAILY_AQI_VALUE']>50, 1,0)
air_2020['moderate+_aqi?'].value_counts()

0    3735
1     273
Name: moderate+_aqi?, dtype: int64

In [218]:
#observation rate of Moderate> Hazardous AQI - 2020
air_2020_moderate_plus = air_2020.groupby('COUNTY').agg({'moderate+_aqi?': 'sum', 'Date': 'count'}).reset_index().rename(columns={'moderate+_aqi?':'moderate_aqi_obs', 'Date':'obs_count'})
air_2020_moderate_plus['2020_moderate_plus_aqi_observed_rate_%'] = air_2020_moderate_plus['moderate_aqi_obs'] / air_2020_moderate_plus['obs_count']
air_2020_moderate_plus = air_2020_moderate_plus[['COUNTY','2020_moderate_plus_aqi_observed_rate_%']]
air_2020_moderate_plus

COUNTY  2020_moderate_plus_aqi_observed_rate_%
0       Albany                                0.113475
1        Bronx                                0.113586
2   Chautauqua                                0.021277
3         Erie                                0.046961
4        Essex                                0.000000
5        Kings                                0.117647
6       Monroe                                0.063574
7     New York                                0.080808
8     Onondaga                                0.046838
9       Orange                                0.041667
10      Queens                                0.068148
11    Richmond                                0.108108
12     Steuben                                0.018223
13     Suffolk                                0.041667

In [219]:
#before merge, check that county name is a match. air_2010_2014_unhealthy has the most county names
air_2010_2014_unhealthy['county_match?'] = np.where(air_2010_2014_unhealthy['COUNTY'].isin(county['county_name'])==True, True, False)
air_2010_2014_unhealthy['county_match?'].value_counts()

True    17
Name: county_match?, dtype: int64

In [220]:
del air_2010_2014_unhealthy['county_match?']

All True. County Name is a perfect match. 

In [221]:
# add to main county df
# 2010 - 2014 
county = county.merge(air_2010_2014_aqi, how='left', left_on='county_name', right_on='COUNTY') #aqi avg
county = county.merge(air_2010_2014_unhealthy, how='left', left_on='county_name', right_on='COUNTY') #unhealthy observation
county = county.merge(air_2010_2014_moderate_plus, how='left', left_on='county_name', right_on='COUNTY') #moderate aqi obs
#2015-2019
county = county.merge(air_2015_2019_aqi, how='left', left_on='county_name', right_on='COUNTY') #aqi avg
county = county.merge(air_2015_2019_unhealthy, how='left', left_on='county_name', right_on='COUNTY') #unhealthy observation
county = county.merge(air_2015_2019_moderate_plus, how='left', left_on='county_name', right_on='COUNTY') #moderate aqi obs
#2020
county = county.merge(air_2020_aqi, how='left', left_on='county_name', right_on='COUNTY') #aqi avg
county = county.merge(air_2020_unhealthy, how='left', left_on='county_name', right_on='COUNTY') #unhealthy observation
county = county.merge(air_2020_moderate_plus, how='left', left_on='county_name', right_on='COUNTY') #moderate aqi obs
county.head()

FIPS  county_name  population    male_%  female_%  65+age_%  5-17age_%  \
0  36001       Albany      305506  0.483846  0.516154  0.174373   0.174373   
1  36003     Allegany       46091  0.508082  0.491918  0.196459   0.196459   
2  36005        Bronx     1418207  0.472109  0.527891  0.133102   0.133102   
3  36007       Broome      190488  0.492656  0.507344  0.194133   0.194133   
4  36009  Cattaraugus       76117  0.497300  0.502700  0.197354   0.197354   

   18-24age_%  white_alone_%  nh_white_alone_%  ...  COUNTY_x  \
0    0.144187       0.757884          0.715682  ...    Albany   
1    0.145083       0.955675          0.942830  ...       NaN   
2    0.097095       0.447241          0.090102  ...     Bronx   
3    0.141757       0.858180          0.827002  ...       NaN   
4    0.090151       0.918573          0.904266  ...       NaN   

   2015-2019_unhealthy_aqi_observed_rate_%  COUNTY_y  \
0                                      0.0    Albany   
1                                      NaN       NaN   
2                                      0.0     Bronx   
3                                      NaN       NaN   
4                                      NaN       NaN   

   2015-2019_moderate_plus_aqi_observed_rate_%  COUNTY_x  2020_avg_daily_aqi  \
0                                     0.101874    Albany           30.384752   
1                                          NaN       NaN                 NaN   
2                                     0.150334     Bronx           31.761693   
3                                          NaN       NaN                 NaN   
4                                          NaN       NaN                 NaN   

   COUNTY_y  2020_unhealthy_aqi_observed_rate_%  COUNTY  \
0    Albany                            0.007092  Albany   
1       NaN                                 NaN     NaN   
2     Bronx                            0.000000   Bronx   
3       NaN                                 NaN     NaN   
4       NaN                                 NaN     NaN   

   2020_moderate_plus_aqi_observed_rate_%  
0                                0.113475  
1                                     NaN  
2                                0.113586  
3                                     NaN  
4                                     NaN  

[5 rows x 40 columns]

In [222]:
county.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 62 entries, 0 to 61
Data columns (total 40 columns):
FIPS                                           62 non-null int64
county_name                                    62 non-null object
population                                     62 non-null int64
male_%                                         62 non-null float64
female_%                                       62 non-null float64
65+age_%                                       62 non-null float64
5-17age_%                                      62 non-null float64
18-24age_%                                     62 non-null float64
white_alone_%                                  62 non-null float64
nh_white_alone_%                               62 non-null float64
black_african_amer_alone_%                     62 non-null float64
amer_indian_alask_alone_%                      62 non-null float64
asian_alone_%                                  62 non-null float64
2+_races_%                     

In [223]:
del county['COUNTY_x']
del county['COUNTY_y']
del county['COUNTY']

In [224]:
county.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 62 entries, 0 to 61
Data columns (total 31 columns):
FIPS                                           62 non-null int64
county_name                                    62 non-null object
population                                     62 non-null int64
male_%                                         62 non-null float64
female_%                                       62 non-null float64
65+age_%                                       62 non-null float64
5-17age_%                                      62 non-null float64
18-24age_%                                     62 non-null float64
white_alone_%                                  62 non-null float64
nh_white_alone_%                               62 non-null float64
black_african_amer_alone_%                     62 non-null float64
amer_indian_alask_alone_%                      62 non-null float64
asian_alone_%                                  62 non-null float64
2+_races_%                     

An important observation is related to collection. NY has 62 counties and it is very large but we have air quality measures of up to 16 counties with only 13 in the last 6+ years. **Data Collection of Air Quality should be auditted** compared to other states and countries.

**Observation Cutoff: December 31st 2020**

In [225]:
covid_daily.Date.max()

Timestamp('2021-01-08 00:00:00')

In [226]:
# cut observations until December 31st 2020
covid_daily = covid_daily.loc[covid_daily['Date']<'2021-01-01']

In [227]:
#confirm 12/31/2020
covid_daily.Date.max()

Timestamp('2020-12-31 00:00:00')

**Add covid mortality data to county df** 

In [228]:
# are observations cumulative?
covid_daily.loc[covid_daily['Date']=='2020-12-31']

countyFIPS         County Name State  stateFIPS       Date  Deaths
1100943       36001       Albany County    NY         36 2020-12-31     202
1100944       36003     Allegany County    NY         36 2020-12-31      72
1100945       36005        Bronx County    NY         36 2020-12-31    5137
1100946       36007       Broome County    NY         36 2020-12-31     202
1100947       36009  Cattaraugus County    NY         36 2020-12-31      42
...             ...                 ...   ...        ...        ...     ...
1101000       36115   Washington County    NY         36 2020-12-31      15
1101001       36117        Wayne County    NY         36 2020-12-31      36
1101002       36119  Westchester County    NY         36 2020-12-31    1664
1101003       36121      Wyoming County    NY         36 2020-12-31      22
1101004       36123        Yates County    NY         36 2020-12-31      10

[62 rows x 6 columns]

In [229]:
#total deaths for 2020
covid_total_2020 = covid_daily.loc[covid_daily['Date']=='2020-12-31'].copy()
len(covid_total_2020)

62

In [230]:
covid_total_2020.rename(columns={'Deaths':'total_covid_deaths'},inplace=True)
covid_total_2020 = covid_total_2020[['countyFIPS', 'total_covid_deaths']]
covid_total_2020

countyFIPS  total_covid_deaths
1100943       36001                 202
1100944       36003                  72
1100945       36005                5137
1100946       36007                 202
1100947       36009                  42
...             ...                 ...
1101000       36115                  15
1101001       36117                  36
1101002       36119                1664
1101003       36121                  22
1101004       36123                  10

[62 rows x 2 columns]

In [231]:
#merge to county df
county = county.merge(covid_total_2020, how='left', left_on='FIPS', right_on='countyFIPS')
county.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 62 entries, 0 to 61
Data columns (total 33 columns):
FIPS                                           62 non-null int64
county_name                                    62 non-null object
population                                     62 non-null int64
male_%                                         62 non-null float64
female_%                                       62 non-null float64
65+age_%                                       62 non-null float64
5-17age_%                                      62 non-null float64
18-24age_%                                     62 non-null float64
white_alone_%                                  62 non-null float64
nh_white_alone_%                               62 non-null float64
black_african_amer_alone_%                     62 non-null float64
amer_indian_alask_alone_%                      62 non-null float64
asian_alone_%                                  62 non-null float64
2+_races_%                     

In [232]:
del county['countyFIPS']

Normalize deaths data by changing per capita

In [233]:
county['covid_deaths_per_capita'] = county['total_covid_deaths'] / county['population']

In [234]:
county.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 62 entries, 0 to 61
Data columns (total 33 columns):
FIPS                                           62 non-null int64
county_name                                    62 non-null object
population                                     62 non-null int64
male_%                                         62 non-null float64
female_%                                       62 non-null float64
65+age_%                                       62 non-null float64
5-17age_%                                      62 non-null float64
18-24age_%                                     62 non-null float64
white_alone_%                                  62 non-null float64
nh_white_alone_%                               62 non-null float64
black_african_amer_alone_%                     62 non-null float64
amer_indian_alask_alone_%                      62 non-null float64
asian_alone_%                                  62 non-null float64
2+_races_%                     

In [235]:
county.iloc[0]

FIPS                                                 36001
county_name                                         Albany
population                                          305506
male_%                                            0.483846
female_%                                          0.516154
65+age_%                                          0.174373
5-17age_%                                         0.174373
18-24age_%                                        0.144187
white_alone_%                                     0.757884
nh_white_alone_%                                  0.715682
black_african_amer_alone_%                        0.141064
amer_indian_alask_alone_%                       0.00304413
asian_alone_%                                     0.068362
2+_races_%                                       0.0289847
hispanic_%                                       0.0625258
sq_miles                                            523.45
pop_in_poverty_%                                     0.1

In [236]:
county['improving_2010-14_vs_2015-19_aqi?'] = np.where(county['2010-2014_avg_daily_aqi'] > county['2015-2019_avg_daily_aqi'], 1, 0)
county['improving_2015-19_vs_2020_aqi?'] = np.where(county['2015-2019_avg_daily_aqi'] > county['2020_avg_daily_aqi'], 1, 0)
county['cont_improve_aqi?'] = np.where((county['improving_2010-14_vs_2015-19_aqi?']==1) & (county['improving_2015-19_vs_2020_aqi?']==1), 1,0)

In [237]:
county.iloc[0]

FIPS                                                 36001
county_name                                         Albany
population                                          305506
male_%                                            0.483846
female_%                                          0.516154
65+age_%                                          0.174373
5-17age_%                                         0.174373
18-24age_%                                        0.144187
white_alone_%                                     0.757884
nh_white_alone_%                                  0.715682
black_african_amer_alone_%                        0.141064
amer_indian_alask_alone_%                       0.00304413
asian_alone_%                                     0.068362
2+_races_%                                       0.0289847
hispanic_%                                       0.0625258
sq_miles                                            523.45
pop_in_poverty_%                                     0.1

In [238]:
# of the counties where we have data, did they improve 2010-2014 period to 2015-2019 period?
county.loc[county['2015-2019_avg_daily_aqi'].isna() == False]['improving_2010-14_vs_2015-19_aqi?'].value_counts()

1    14
Name: improving_2010-14_vs_2015-19_aqi?, dtype: int64

All 14 counties did

In [239]:
county.loc[county['2015-2019_avg_daily_aqi'].isna() == False]['improving_2015-19_vs_2020_aqi?'].value_counts()

1    8
0    6
Name: improving_2015-19_vs_2020_aqi?, dtype: int64

In [240]:
6/14

0.42857142857142855

But 6/14 counties with data (over 40% counties) dipped from in 2020 compared to the previous 5 years.

## 4) Exploratory Data Analysis <a class="anchor" id="eda"></a>

Note the following:
* COVID Observation Cutoff: December 31st 2020
* "Sex" as Male/Female comes directly from the U.S. Census data. We understand "sex" is a larger spectrum and this is an oversimplified classification.
* Unemployment rate from 2019


**Improvements in AQI?**

In [241]:
# of the counties where we have data, did they improve 2010-2014 period to 2015-2019 period?
county.loc[county['2015-2019_avg_daily_aqi'].isna() == False]['improving_2010-14_vs_2015-19_aqi?'].value_counts()

1    14
Name: improving_2010-14_vs_2015-19_aqi?, dtype: int64

All 14 counties were improving their air quality from the 2010-2014 range to the 2015-2019 range. Great! 

In [242]:
county.loc[county['2015-2019_avg_daily_aqi'].isna() == False]['improving_2015-19_vs_2020_aqi?'].value_counts()

1    8
0    6
Name: improving_2015-19_vs_2020_aqi?, dtype: int64

However, 6 counties (out of 14, over ~40%) had worse air quality in 2020 than in the 5-year period before

In [243]:
county.loc[county['2015-2019_avg_daily_aqi'].isna() == False].loc[county['improving_2015-19_vs_2020_aqi?']==0]

FIPS county_name  population    male_%  female_%  65+age_%  5-17age_%  \
0   36001      Albany      305506  0.483846  0.516154  0.174373   0.174373   
2   36005       Bronx     1418207  0.472109  0.527891  0.133102   0.133102   
27  36055      Monroe      741770  0.482062  0.517938  0.178620   0.178620   
33  36067    Onondaga      460528  0.482229  0.517771  0.175338   0.175338   
42  36085    Richmond      476143  0.485841  0.514159  0.166549   0.166549   
50  36101     Steuben       95379  0.498286  0.501714  0.201418   0.201418   

    18-24age_%  white_alone_%  nh_white_alone_%  ...  \
0     0.144187       0.757884          0.715682  ...   
2     0.097095       0.447241          0.090102  ...   
27    0.097026       0.768343          0.701208  ...   
33    0.101675       0.799626          0.764627  ...   
42    0.081826       0.744654          0.595811  ...   
50    0.074671       0.947525          0.934126  ...   

    2015-2019_unhealthy_aqi_observed_rate_%  \
0                                       0.0   
2                                       0.0   
27                                      0.0   
33                                      0.0   
42                                      0.0   
50                                      0.0   

    2015-2019_moderate_plus_aqi_observed_rate_%  2020_avg_daily_aqi  \
0                                      0.101874           30.384752   
2                                      0.150334           31.761693   
27                                     0.087929           26.740550   
33                                     0.052609           24.995316   
42                                     0.151515           32.000000   
50                                     0.033713           22.152620   

    2020_unhealthy_aqi_observed_rate_%  \
0                             0.007092   
2                             0.000000   
27                            0.000000   
33                            0.000000   
42                            0.000000   
50                            0.000000   

    2020_moderate_plus_aqi_observed_rate_%  total_covid_deaths  \
0                                 0.113475                 202   
2                                 0.113586                5137   
27                                0.063574                 563   
33                                0.046838                 426   
42                                0.108108                1278   
50                                0.018223                 120   

    covid_deaths_per_capita  improving_2010-14_vs_2015-19_aqi?  \
0                  0.000661                                  1   
2                  0.003622                                  1   
27                 0.000759                                  1   
33                 0.000925                                  1   
42                 0.002684                                  1   
50                 0.001258                                  1   

    improving_2015-19_vs_2020_aqi?  cont_improve_aqi?  
0                                0                  0  
2                                0                  0  
27                               0                  0  
33                               0                  0  
42                               0                  0  
50                               0                  0  

[6 rows x 36 columns]

In [244]:
county.loc[county['2015-2019_avg_daily_aqi'].isna() == False].loc[county['improving_2015-19_vs_2020_aqi?']==0]['county_name'].unique()

array(['Albany', 'Bronx', 'Monroe', 'Onondaga', 'Richmond', 'Steuben'],
      dtype=object)

The **6 counties where air quality decreased in 2020 were Albany, Bronx, Monrow, Onondaga, Richmond, and Steuben**

In [245]:
county['aqi_change_2015-19_vs_2020_%'] = (county['2020_avg_daily_aqi']-county['2015-2019_avg_daily_aqi'])/county['2015-2019_avg_daily_aqi']

In [246]:
county.iloc[0]

FIPS                                                 36001
county_name                                         Albany
population                                          305506
male_%                                            0.483846
female_%                                          0.516154
65+age_%                                          0.174373
5-17age_%                                         0.174373
18-24age_%                                        0.144187
white_alone_%                                     0.757884
nh_white_alone_%                                  0.715682
black_african_amer_alone_%                        0.141064
amer_indian_alask_alone_%                       0.00304413
asian_alone_%                                     0.068362
2+_races_%                                       0.0289847
hispanic_%                                       0.0625258
sq_miles                                            523.45
pop_in_poverty_%                                     0.1

In [247]:
county.loc[county['2015-2019_avg_daily_aqi'].isna() == False].loc[county['improving_2015-19_vs_2020_aqi?']==0]

FIPS county_name  population    male_%  female_%  65+age_%  5-17age_%  \
0   36001      Albany      305506  0.483846  0.516154  0.174373   0.174373   
2   36005       Bronx     1418207  0.472109  0.527891  0.133102   0.133102   
27  36055      Monroe      741770  0.482062  0.517938  0.178620   0.178620   
33  36067    Onondaga      460528  0.482229  0.517771  0.175338   0.175338   
42  36085    Richmond      476143  0.485841  0.514159  0.166549   0.166549   
50  36101     Steuben       95379  0.498286  0.501714  0.201418   0.201418   

    18-24age_%  white_alone_%  nh_white_alone_%  ...  \
0     0.144187       0.757884          0.715682  ...   
2     0.097095       0.447241          0.090102  ...   
27    0.097026       0.768343          0.701208  ...   
33    0.101675       0.799626          0.764627  ...   
42    0.081826       0.744654          0.595811  ...   
50    0.074671       0.947525          0.934126  ...   

    2015-2019_moderate_plus_aqi_observed_rate_%  2020_avg_daily_aqi  \
0                                      0.101874           30.384752   
2                                      0.150334           31.761693   
27                                     0.087929           26.740550   
33                                     0.052609           24.995316   
42                                     0.151515           32.000000   
50                                     0.033713           22.152620   

    2020_unhealthy_aqi_observed_rate_%  \
0                             0.007092   
2                             0.000000   
27                            0.000000   
33                            0.000000   
42                            0.000000   
50                            0.000000   

    2020_moderate_plus_aqi_observed_rate_%  total_covid_deaths  \
0                                 0.113475                 202   
2                                 0.113586                5137   
27                                0.063574                 563   
33                                0.046838                 426   
42                                0.108108                1278   
50                                0.018223                 120   

    covid_deaths_per_capita  improving_2010-14_vs_2015-19_aqi?  \
0                  0.000661                                  1   
2                  0.003622                                  1   
27                 0.000759                                  1   
33                 0.000925                                  1   
42                 0.002684                                  1   
50                 0.001258                                  1   

    improving_2015-19_vs_2020_aqi?  cont_improve_aqi?  \
0                                0                  0   
2                                0                  0   
27                               0                  0   
33                               0                  0   
42                               0                  0   
50                               0                  0   

    aqi_change_2015-19_vs_2020_%  
0                       0.093324  
2                       0.053366  
27                      0.009878  
33                      0.093209  
42                      0.033744  
50                      0.056445  

[6 rows x 37 columns]

In [248]:
county.loc[county['2015-2019_avg_daily_aqi'].isna() == False].loc[county['improving_2015-19_vs_2020_aqi?']==0]['aqi_change_2015-19_vs_2020_%'].describe()

count    6.000000
mean     0.056661
std      0.032877
min      0.009878
25%      0.038650
50%      0.054906
75%      0.084018
max      0.093324
Name: aqi_change_2015-19_vs_2020_%, dtype: float64

In [249]:
#Sort counties with deteriorating air pollution by % air pollution increase
county.loc[county['2015-2019_avg_daily_aqi'].isna() == False].loc[county['improving_2015-19_vs_2020_aqi?']==0][['county_name','aqi_change_2015-19_vs_2020_%']].sort_values(by='aqi_change_2015-19_vs_2020_%', ascending=False)

county_name  aqi_change_2015-19_vs_2020_%
0       Albany                      0.093324
33    Onondaga                      0.093209
50     Steuben                      0.056445
2        Bronx                      0.053366
42    Richmond                      0.033744
27      Monroe                      0.009878

In [250]:
data = county.loc[county['2015-2019_avg_daily_aqi'].isna() == False].loc[county['improving_2015-19_vs_2020_aqi?']==0][['county_name','aqi_change_2015-19_vs_2020_%']].sort_values(by='aqi_change_2015-19_vs_2020_%', ascending=False)
data - 

SyntaxError: invalid syntax (<ipython-input-250-30096a97dc52>, line 2)

In [ ]:
data = county.loc[county['2015-2019_avg_daily_aqi'].isna() == False]
ax = sns.barplot(x="aqi_change_2015-19_vs_2020_%", y="county_name", data=data, color='red').set_title('Counties by Change in Air Pollution');
plt.xlabel("% Change in Air Pollution")
plt.ylabel("County Name");

Of the counties increasing air pollution, this increased can be up to a 10% increase with Albany and Onondaga in the worse condition.

**Correlation Analysis**

In [ ]:
rs = np.random.RandomState(0)
df = pd.DataFrame(rs.rand(10, 10))
corr = county.corr()
corr.style.background_gradient(cmap='coolwarm')

In this heat map, the closer to 1 (positive correlation) or -1 (negative correlation) shows a correlation. 0 means no correlation. A negative correlation means that as one goes up, the other goes down. A positive corelation means that as variable goes up the other goes up too OR when one goes down, the other goes down too (basically they go the same direction). Some records were null but as per [this source](https://www.geeksforgeeks.org/python-pandas-dataframe-corr/#:~:text=corr()%20is%20used%20to,the%20dataframe%20it%20is%20ignored.), the corr() methos used excludes the null. *Correlations with population, hospital beds, or square miles are not meaningful as we expect more deaths when there is more population.* 

When looking at correlation with covid_deaths_per_capita, the following variables (with exceptions above) have correlation above 0.5 or below -0.5 hence there are strong positive or negative corelations.
* nh_white_alone_%	-0.833116
* white_alone_%	-0.810306
* black_african_amer_alone_%	0.777036
* hispanic_%	0.773217
* asian_alone_%	0.690696
* 2015-2019_moderate_plus_aqi_observed_rate_%	0.685503
* 2020_moderate_plus_aqi_observed_rate_%	0.653416
* 2010-2014_avg_daily_aqi	0.628852
* 2010-2014_moderate_plus_aqi_observed_rate_%	0.624889
* pop_density	0.623241
* 2015-2019_avg_daily_aqi	0.583343
* 2020_avg_daily_aqi	0.570557
* improving_2010-14_vs_2015-19_aqi?	0.545156
* male_%	-0.514211
* female_%	0.514211


The image below isolates this correlations: 

![Correlation to Covid Deaths Per Capita](./img/corr.jpg)

We can clearly see **inequalities related to race and ethnicity** significantly affecting covid deaths per capita. The most prominent is the negative correlation between the proportion of the population that is white (particularly non-hispanic white) and covid deaths per capita with every % increase in covid deaths per capita the proportion of population that is white decreses almost 1-to-one. The opposite happens with Black and African Americas, Hispanics, and even Asians when as covid deaths per capita increase, there is likely more of these groups in the population.

In addition, we find interesting correlations relating to air quality with the strongest correlation showing that **as the frequency of air quality observations classified moderate to hazardous increases, so does covid deaths per capita** in that county. We can also see (although less strongly) that as **average AQI increases, so does COVID mortality**. A crucial finding is that **air quality variables have a stronger correlation with covid deaths per capita than population density** which defies the expected based on what the public has been informed.

## 5) Hypothesis Test <a class="anchor" id="htest"></a>

## 6) Regression Analysis <a class="anchor" id="regression"></a>

With so little data, this is not the most meaningful regression but a baseline method that can be applied to more counties where air quality data is available. 

Let's use the variables identified to have correlation in a regression analysis.

In [ ]:
data = county[['covid_deaths_per_capita','nh_white_alone_%', 'white_alone_%', 'black_african_amer_alone_%', 'hispanic_%', 'asian_alone_%' ,'2015-2019_moderate_plus_aqi_observed_rate_%','2020_moderate_plus_aqi_observed_rate_%', '2010-2014_avg_daily_aqi','2010-2014_moderate_plus_aqi_observed_rate_%','pop_density','2015-2019_avg_daily_aqi','2020_avg_daily_aqi','improving_2010-14_vs_2015-19_aqi?','male_%','female_%']]
data.head()

## 7) Conclusion <a class="anchor" id="conclusion"></a>

?

In [ ]:
# NY County Dataframe created
county.to_csv(r'./data/final_county.csv', index = False)

Data aggregated for this analysis saved as "final_county.csv" in the data subfolder of this repository.

If you are wondering, how is the air quality in your area right now. Enter your Zip Code here: https://www.airnow.gov/?city=Bronx&state=NY&country=USA

## 8) Project Next Steps <a class="anchor" id="next"></a>

* A closer look at the impact of race and ethnicity in covid mortality rate.